### ISSUE TITLE
CUT Wrong layer name

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#100]
@gamaliel and @monica can you change the Entrances layer to Entrance?

**Comment by agrignard** [comment]
@milkmonica , @gamalielpalomo , @LAAP @markus, can you tell me how to edit a layer in Autocad 2019??? in Autocad 2018 i just had to click on the layer and change its name, it seems that autocad 2019 is different nothing happen when I click or right click on the later.

<img width="1789" alt="Screenshot 2020-08-17 at 16 26 52" src="https://user-images.githubusercontent.com/3928502/90407283-a1162f00-e0a6-11ea-84d4-b4881eeb3b95.png">

BTW the goal of this issue is only to remove the later "S" from the layer... I guess it should be doable by AUTOCAD user right?

**Comment by MarkusElKatsha** [comment]
There are a few ways to change the layer name. If you are looking to change the layer name for ALL lines on that layer, then you change the GLOBAL layer name in the upper right zone of the LAYER Dialogue box. 

If you are looking to change the layer of a specific line, or group of lines, then you use the LAYER PROPERTY dialog box in the lower right panel under the LAYER tab.

Select the line(s) you want to change then on the lower right under the Layer box, select the desired layer you are looking for. Let me know if this helps. M

**Comment by agrignard** [comment]
Yes this is what I am saying but I have no way to edit the global layer in the upper right. Is there anyone that can have a look to see if it comes from my autocad 2019 or from the file it self?

**Comment by agrignard** [comment]
<img width="1207" alt="Screenshot 2020-08-18 at 15 14 44" src="https://user-images.githubusercontent.com/3928502/90517373-99698f80-e165-11ea-9746-84556f7235b5.png">
 This is what I get now...

**Comment by MarkusElKatsha** [comment]
can we look at this right after our meeting? You have an active command open. Lets do this though zoom

**Comment by agrignard** [comment]
Can you see if it works on yours???

https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/CUT/building.dxf

**Comment by MarkusElKatsha** [comment]
Where is the file stored?

**Comment by agrignard** [comment]
Here!https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/CUT/building.dxf
