### ISSUE TITLE
Episode 1: Masks in Classroom with Natural Ventilation (CUCS)

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#107]
Site: **UDG/CUCS/Level 2**
**2 sub episode**: No Mask (big sprawl) and mask (lower sprawl)

Density Scenario: people are place with a distance of **2 meter** (if we have the real desk that could be possible to run it)
Mask: **0 to 0.5** (or other value as you wish)

Code to run (and edit) in ````StoryTelling.gaml`````

``````
experiment Episode1 type: gui parent: Coronaizer{
	parameter 'fileName:' var: useCase category: 'file' <- "UDG/CUCS/Level 2";
	parameter "Density Scenario" var: density_scenario category:'Initialization'  <- "distance" among: ["data", "distance", "num_people_building", "num_people_room"];
	parameter 'distance people:' var: distance_people category:'Visualization' min:0.0 max:5.0#m <- 2.0#m;
	parameter "Mask Ratio:" category: "Policy" var: maskRatio min: 0.0 max: 1.0 step:0.1 <-0.5;
}
``````

This is how it look so far 
<img width="1305" alt="Screenshot 2020-08-24 at 12 29 25" src="https://user-images.githubusercontent.com/3928502/91034608-8f340f00-e605-11ea-887e-73e832865adc.png">

**Comment by LAAP** [comment]
Hi @agrignard , some small clarifications:

**2 sub episode:** 

_Pre-COVID19_ = No Mask (big sprawl) and 
_COVID19_ = mask (lower sprawl)

Density Scenarios:

_Pre-COVID19_ = 30 students per room
_COVID19_ = people are place with a distance of **2 meter** (if we have the real desk that could be possible to run it)

The rest as you have it below.

**Comment by LAAP** [comment]
Hi @agrignard , some small clarifications:

**2 sub episode:** 

_Pre-COVID19_ = No Mask (big sprawl) and 
_COVID19_ = mask (lower sprawl)

Density Scenarios:

_Pre-COVID19_ = 30 students per room
_COVID19_ = people are place with a distance of **2 meter** (if we have the real desk that could be possible to run it)

The rest as you have it below

**Comment by agrignard** [comment]
Ok so as it has been request in this issue the Episode 1 has been produced here:
https://drive.google.com/file/d/144Elt3EqB7fbl9q3mvaqEep9ah1HOWs0/view?usp=sharing 

It is so far the official Episode, we will wait for feedback and produce another one if needed

**Comment by LAAP** [comment]
@agrignard ,

The video is cool. However, I think that scenario "A" is a bit extreme... Maybe we can start with less "infected people"? Not sure.

Also, there are things that I am missing:

- Starting number of "potentially infected students"
- Potential "R0 (level of infection)" used in the simulation in each scenario
- Number of students per classroom
- Maybe: A "Big" Indicator giving the % of "potential infection"
- Maybe a a clock showing the 3h (in A) and the 45min (in B)

**Comment by agrignard** [comment]
Yep this is the beta rehearse Episode and I can enhance it (I would prefer to have feedback from  Carlos and Mayra first) and that's why the issue is not close. I agree it's abit to extreme

- Starting number of "potentially infected students" => 10 it's wriiten on, top of the high and low risk. Its a parameter taht w can change if we want

- Potential "R0 (level of infection)" used in the simulation in each scenario=> we don't compute that anymore it's not relevant at all at this scale

- Number of students per classroom=> how do you want it to be displayed? per classromms? Rigth now it's not per class room it's with the distance as agreed but it could hve been per class rooms (mayeb we can keep it for another episode)

- Maybe: A "Big" Indicator giving the % of "potential infection"=> how to compute this?

- Maybe a a clock showing the 3h (in A) and the 45min (in B)=> in this episode this is not clear for me right now we just show influence of mask and distance but not abotu the stay in the room, so same we need to agree, i think it's too much to show 3 stuff or we need maybe 4 scenario... (A nothing, B(mask), C (distance), D(stay in room) again everything is possible just a question of "coordination" ;-)

**Comment by milkmonica** [comment]
I asked Mayra to solve this issue right now, she tells me that she agrees with Luis, that in scenario "A" they get infected very quickly. In the previous simulation, they entered the classroom “healthy” and the risk of infection occurred when leaving the classroom (in the 5 min in which they changed classrooms)

**Comment by LAAP** [comment]
Dear @milkmonica ,

Yes, this simulation is a bit "extreme", however, the virus now is airborne and things has changed. I recommend to look into this article:

https://www.wsj.com/articles/key-to-preventing-covid-19-indoors-ventilation-11598953607

- The new distance is 26 feet
- The small Aerosols Can linger for hours in the air
- Small Droplets and Large Aerosols Can linger in the air for 30 minutes or more

So, if people do not follow CDC rules like: use masks, keeps the paths, keeps some physical distance, sanitation points, etc. Then, the risk of infection is very high.

I was asking to @agrignard , to have a "scale" of color so people can go from low risk (green) to middle risk (Yellow/orangish) and after high risk (red). But that will take some time to develope

**Comment by agrignard** [comment]
"I was asking to @agrignard , to have a "scale" of color so people can go from low risk (green) to middle risk (Yellow/orangish) and after high risk (red). But that will take some time to develop" => see https://github.com/CityScope/CS_Proxymix/issues/124

**Comment by agrignard** [comment]
@gamalielpalomo and @milkmonica now that most of the feature are finally here and all the dxf are all ready  can you start to propose some content for this Episode? Let me know if you have any trouble to produce video with GAMA

**Comment by LAAP** [comment]
@agrignard ,

Let me see if I am understanding you correctly: I think that @gamalielpalomo and @milkmonica can give us the UDG protocols for the "Rump up"; as an example In Episode 1, "UDG is planning to have 50% of students in the classrooms", or "the will keep "2m distance per student in the classrooms" etc., so we can adapt the UDG protocols to the final simulations. 

However, we will produce the final simulations for the UDG videos. Isn't it?

Please, let me know your thoughts

**Comment by agrignard** [comment]
Yes Rump up is for sure mandatory. But I was also thinking that it would be great and an indicator of successful collaboration in term of transfer of knowledge to be sure that the UdF team can produce video (that would be validated by us later).

@gamalielpalomo and @milkmonica any thought?

**Comment by LAAP** [comment]
I see @agrignard ,

It make sense. Yes, I think that it is a good idea having @gamalielpalomo and @milkmonica making a test running GAMA an making a video from GAMA just for educational purposes, so we can learn together how to make videos with GAMA, so in the future we already have that training.

Please, @gamalielpalomo and @milkmonica , let us know your thoughts

**Comment by agrignard** [comment]
Update on this issue to try to reach a common agreement. This is what we have so far on the 9/9/20. All the information appears (time spend, ratio of mask, distance, number of low, medium, high rsk, etc)

This is the status of the building just before people leave the space (10am in scenario A, 7.45am in scenario B)
Scenario A
<img width="1236" alt="Screenshot 2020-09-09 at 13 25 15" src="https://user-images.githubusercontent.com/3928502/92592656-3a002a80-f2a0-11ea-9cdb-012ff1648c77.png">
Scenario B
<img width="1636" alt="Screenshot 2020-09-09 at 13 24 37" src="https://user-images.githubusercontent.com/3928502/92592697-48e6dd00-f2a0-11ea-8ea1-d71268f61fbe.png">


Would be great to validate this one so we can produce and finish the first video. As it is I consider it as final unless I get "doable" request

**Comment by LAAP** [comment]
Hi @agrignard ,

This is great, Awesome job! 

Just a last question, Can we show a bit (maybe in a very transparent background in the rooms) the "Pollution map" (or Risk level "green to red" of the rooms) that you have made in a previous model?. I don't remem in which issue

**Comment by agrignard** [comment]
Yep good idea.
It's a parameter to set to true or false. I set to true now for all the episode. Looks pretty cool indeed
<img width="1633" alt="Screenshot 2020-09-09 at 17 06 20" src="https://user-images.githubusercontent.com/3928502/92616748-e81acd00-f2be-11ea-9394-acb66bd3fe46.png">

**Comment by LAAP** [comment]
@agrignard ,

Beautiful!!!!!! I love it!!!!   ;)

**Comment by LAAP** [comment]
From the videos sent by @agrignard 

- **Episode1_A:** It looks Great: I love the way we show how people gets potentially infected in a gradual way (from green to red), and how spaces gets also in a high level of risks, after spending 3h in the classroom

- **Episode1_B:** I really like it: It works very well showing that 45min + Masks, + Social distancing reduces the risk of infection

From my point of view, Episode 1 is ready for the final cut. Please let me know your thoughts

**Comment by agrignard** [comment]
OK great! We are close to close this issue then.

I agree with you the Episode 1 is the most compelling so far and I don't see what can be improved so far

**Comment by LAAP** [comment]
Yes. Let's see

**Comment by agrignard** [comment]
I consider this Episode done
