### ISSUE TITLE
Episode 5: Social distance, masks and dedicated Paths in an open space - (CUSUR)

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#111]
Site: **UDG/CUSUR** **WE DON'T HAVE IT SO FAR** 
**Episode**: How people can get infected in the open space without following the rules vs following the rules.

Density Scenario: people are place with a distance of **2 meter** (if we have the real desk that could be possible to run it)

Code to run (and edit) in **StoryTelling.gaml**

``````
experiment Episode5 type: gui parent: Coronaizer{
	parameter 'fileName:' var: useCase category: 'file' <- "UDG/CUSUR";
	parameter "Density Scenario" var: density_scenario category:'Initialization'  <- "distance" among: ["data", "distance", "num_people_building", "num_people_room"];
	parameter 'distance people:' var: distance_people category:'Visualization' min:0.0 max:5.0#m <- 2.0#m;
}
``````

This is how it look so far 
**WE CANNOT SHOW ANYTHING SO FAR**

**Comment by LAAP** [comment]
Hi @agrignard , some small clarifications:

**2 sub episode:** 

_Pre-COVID19_ = No Mask (big sprawl), no line, no distance, no control points, no hygienic measures, and 
_COVID19_ = mask (lower sprawl) and following all the rules

Density Scenarios:

_Pre-COVID19_ = @gamalielpalomo and @milkmonica , how many people uses the campus in a normal day pre-COVID crisis? 
_COVID19_ = people following the rules, 2 meters, but also 2 or 3 shifts, so less people in the campus (50% less population)

The rest as you have it above

**Comment by agrignard** [comment]
First version of this episode

<img width="1497" alt="Screenshot 2020-08-28 at 18 52 31" src="https://user-images.githubusercontent.com/3928502/91593027-bcfbb980-e95f-11ea-9079-8d84e49d749a.png">

**Comment by agrignard** [comment]
@gamalielpalomo and @milkmonica now that most of the feature are finally here and all the dxf are all ready  can you start to propose some content for this Episode? Let me know if you have any trouble to produce video with GAMA

**Comment by agrignard** [comment]
update on 09/09/20

Dxf is working but there are still a feature missing
@gamalielpalomo and @milkmonica if we want to illustrat the use of specifi path, we will need to have it. Or to generate it? I discuseed with @gamalielpalomo and this can be easily done in QGIS (replacing the pedestrian path)

Also as the site is very big the simualtion is very slow to run (but running)

<img width="1792" alt="Screenshot 2020-09-09 at 14 37 23" src="https://user-images.githubusercontent.com/3928502/92599080-06c29900-f2aa-11ea-9c86-d7639a2501c7.png">
<img width="1792" alt="Screenshot 2020-09-09 at 14 37 30" src="https://user-images.githubusercontent.com/3928502/92599096-0a562000-f2aa-11ea-8eb1-20701d85bf25.png">

**Comment by LAAP** [comment]
From the videos sent by @agrignard:

Episode 5 is a bit confusing. I think we are mixing scenarios, in episode A, "NO INTERVENTION", we have less people on campus than in B, "INTERVENTION", less infected people than in B, and they stay less time than in B. Also I think that we need to have a bigger population in the campus. A couple of thousands of people, if possible. This is the detailed note:

- **Episode5_A:** "NO INTERVENTION": We have 252 people less than the 310 people from scenario B, We have 5 infected people and in B we have 22. And people spend 23min in the campus, in B 50min. Can we?:
-Increment the number of people in the campus to between 20k or 2k?
-People spend more time on the campus (3h to 9h?)
-People randomly change from one building to another every 3h, or every x time

- **Episode5_B:** "DEDICATE PATH": What already has been said above can be used to modify this scenario. However, the dedicated path, lines, waiting lines, etc. are not very clear... Building in the top of that:
-Density: Use the 50% of the population from "5_A"
-Time: People spends from 1h to 3h in the campus
-Population: People randomly change from one building to another every 45min, or every x time
-Everyone should keep the 4m physical distance all the time (or/and the lines): When people leaves the place the aglomerate a bit

I hope that this long email will be useful.

**Comment by agrignard** [comment]
Ok thank for the update, this one is a bit trickier as there is lot of people in the campus. 

Compare to the other Episode it's almost a new and more complex model so we will se what we can do , but maybe the priority will be to finsih until Episode 4

**Comment by LAAP** [comment]
@agrignard ,

I see. Also, in this episode, in scenario A I see students being "produced" right in the door of the building (at the left side), and "killed" as soon as they get in the building. That doesn't happen in scenario B

**Comment by agrignard** [comment]
I consider this Episode as alomost done. Feel to reopen a specific issue if needed. #162 is still open for a very tiny detail

**Comment by LAAP** [comment]
@agrignard , Can you share a video of the final Episode 2 before closing this Episode?

**Comment by milkmonica** [comment]
Last week Gama and I were working on adding a border to the .dxf throughout the building (according to Luis's recommendation), we did tests and it seems to us that this can help the pedestrian. 

I've had a lot of problems making the pull requests, so if it's okay with you, I'll share the link of the drive where these changes were left, we'll be uploading it in a pull as appropriate shortly, but I'm worried that we're stopping you if we keep waiting to upload it:
https://drive.google.com/drive/u/1/folders/1jtWgIWJML2tFHF64AmfclL87420qr7FS

Let me know if this logic is correct or you need another change in the DXF, consider that I will do it shortly, but without testing in GAMA and attaching it to the drive!

**Comment by agrignard** [comment]
Would be great to have a better dxf. However we are in the process of producing the video so I am afraid it's a bit too late.

Also I just tried to integrate it t there are something weird with it.

it would be great if you can validate first your dxf before to send it

This is what I have so far (so for now we keep the current one)
<img width="783" alt="Screenshot 2020-09-29 at 19 19 47" src="https://user-images.githubusercontent.com/3928502/94591863-e96d6300-0288-11eb-8df7-802544ce9067.png">

**Comment by milkmonica** [comment]
Yes I understand, for now Gama is not able to validate them
Let's leave it as it is then! thank you very much Arnaud! I will keep an eye on anything.

**Comment by agrignard** [comment]
As we are now starting the validation process of this model and that the final video has been released I consider these Episode issues as closed. Please feel free to reopen it or to create more specific issue related to the model itself not to the Video
