### ISSUE TITLE
CUCEA DXF 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#112]
@gamalielpalomo and @milkmonica the CUCEA DXF is not produced yet for the Episode 4 see #110

**Comment by agrignard** [comment]
A first version fot eh dxf has been pushed here https://github.com/CityScope/CS_Proxymix/pull/115  but there is still a problem to generate the pedestrian network.

By looking at the error , it clearly seems that there are some shapes in the AUTOCAD that are wrong and that cannot be traingulated by GAMA. IS tehre an Autocad expert that can check the validity of each shape of this dxf?

`````
2 occurrences in 2 agents at cycle 0: Java error: exception in JTS library
in create triangles from: triangulate(t,tol_cliping,tol_triangulation) ;
ConstraintEnforcementException: Too many splitting iterations while enforcing constraints.  Last split point was at:  [ POINT ( 11.409305120877422 37.634857430092296 ) ]
com.vividsolutions.jts.triangulate.ConformingDelaunayTriangulator.enforceConstraints(ConformingDelaunayTriangulator.java:421)
com.vividsolutions.jts.triangulate.ConformingDelaunayTriangulationBuilder.create(ConformingDelaunayTriangulationBuilder.java:123)
com.vividsolutions.jts.triangulate.ConformingDelaunayTriangulationBuilder.getTriangles(ConformingDelaunayTriangulationBuilder.java:199)
msi.gama.common.geometry.GeometryUtils.triangulation(GeometryUtils.java:494)
msi.gaml.operators.Spatial$Transformations.triangulate(Spatial.java:2700)
gaml.additions.GamlAdditions.lambda$859(GamlAdditions.java:922)
msi.gaml.expressions.AbstractNAryOperator._value(AbstractNAryOperator.java:302)
when applying the triangulate operator on [walking_area0, 0.1, 0.0]
in create triangles from: triangulate(t,tol_cliping,tol_triangulation) ;
`````

**Comment by agrignard** [comment]
Maybe @ptaillandier can also (if he has time) have a look at this one

**Comment by agrignard** [comment]
Thank you @ptaillandier !! However it seems that the dxf is a bit too complex, if uyou have identify the object that seems suspucious maybe you can explain it here and see if @gamalielpalomo and @milkmonica can fix it?

**Comment by gamalielpalomo** [comment]
We made a PR with dxf working. Can you check it @agrignard ?

**Comment by agrignard** [comment]
Ok it's workign now. good job! One more to go #113

**Comment by gamalielpalomo** [comment]
Ok. When you run daily routine, can you see the agents? When I did it, it seems to work fine but agents are not visualized

**Comment by agrignard** [comment]
Yes agent are not visualize because they are not speicy in the DailyRoutine model but only in the CityScope Coronizer showing the ViralPeople (red of green)
