### ISSUE TITLE
Have a way to define the time spent in a room

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#117]
Right now the time people spend in a room is kind of hardcoded (actually I don't remember exactly how and where? are we using the activity?)

It would be great if we can use a parameter for that. Rigth now there is this variable ````timeSpent```` which is used only in the display, if it can be used in the model that would be great

**Comment by LAAP** [comment]
Hi @agrignard ,

As I have commented in a reopened issue,  I think time in the room is important. I think that, if we can't calculate the time from the simulation, at least we should follow the IDSS graph below.

Seems to me that, **if we follow the 0.003 curve** (and if we integrated in the simulation), we will be in the side of safety: in this curve, **30 people** in a room with masks and keeping social distancing can not stay longer than **45-60 min**:


<img width="991" alt="Captura de pantalla 2020-08-26 a las 10 58 30" src="https://user-images.githubusercontent.com/19315213/91320268-53c34d00-e78b-11ea-8124-909faa5affc9.png">
Please, let me know your thoughts

Luis

**Comment by LAAP** [comment]
Hi @agrignard ,

I think that each Episode may be a combination of both. In some Episodes, **like Episode1-Classrooms, Episode2-Labs, and Episode5-Campus** I think that UDG knows that they want to **reduce students/population/density into 50%**. In other episodes, like the **Episode3-office and Episode4-Library**, they are not that sure, so maybe we can run and "optimization" simulation, previous the final videos. What do you think?

I re-open this issue so @milkmonica and @gamalielpalomo can help us with the UDG standards.

Please, correct me is I am wrong, but so far, this are the number of students reduction:

- Episode-1 Classrooms = -50%

**Comment by LAAP** [comment]
Hi @agrignard ,

I think that each Episode may be a combination of both. In some Episodes, **like Episode1-Classrooms, Episode2-Labs, and Episode5-Campus** I think that UDG knows that they want to **reduce students/population/density into 50%**. In other episodes, like the **Episode3-office and Episode4-Library**, they are not that sure, so maybe we can run and "optimization" simulation, previous the final videos. The challenge is also **the time spent indoors in each episode**, I think that will depend on infection risk **coming from the simulation** . What do you think?

I re-open this issue so @milkmonica and @gamalielpalomo can help us with the UDG standards.

Please, correct me is I am wrong, but so far, this are the number of students reduction:

- Episode-1 Classrooms = -50% of reduction, time TBD (probably shifts of 45min)

- Episode-2 Lab = -50% of reduction, time TBD (probably shifts of 45min)

- Episode-3 office building = TBD, time TBD 

- Episode-4 Library = TBD, time TBD 

- Episode-5 Campus = -50% of reduction, Time TBD (Probably With 2 big shifts)

**Comment by agrignard** [comment]
The problem of the" _50% reduction_"  is...  **50% of What???** as we don't have the initial number...

The only thing we have is the intial layout of the desk and when we use it we put one personne per desk but I don't think this is realist

@gamalielpalomo and @milkmonica can you help us on this?

**Comment by agrignard** [comment]
I think we can close this issue if we don't have any new input
