### ISSUE TITLE
Have a pie that represents the number of high risk people vs low risk

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#118]
(It could be cool to have a dynamic visual way to show it. The Pie can show, in real time, just with colors, how "High risk infected people are growing depending on how people follow the rules or not. The Pie could have the green (low), orange/yellow (medium), and red (high) colors, changing in parallel with the numbers: Visual inputs are usually easier to understand than numbers by students and citizens)

This should be quiet easy as we already have the updated parameter ````nb_susceptible````and ````nb_infected````

**Comment by LAAP** [comment]
Awesome @agrignard !

**Comment by agrignard** [comment]
See #114 and recent improvement
