### ISSUE TITLE
Have real time fever chart in the simuation

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#119]
We already have it as a separeted window, but it doesn't look very graphics... let's sse if we can embed it in the simualtion  it self (shoudl be doable)

**Comment by LAAP** [comment]
Ok @agrignard , I think aesthetics are important, it could be cool to have @markus involved on this design issue, if not, I will try to put some time on it

**Comment by markus** [comment]
@LAAP, you mentioned my github username, but I suppose you mean someone else.

**Comment by LAAP** [comment]
@markus, Sorry about that it is another "markus" from the CS group... @agrignard , what is "Markus-CS" Github user name?

**Comment by agrignard** [comment]
Shoudl something like @MarkusElKatsha but as often with Markus for a certain reason you cannot tag him automatically with @... I think this is because he never contributed (by doign a commit) to this github. I am keeping asking him to contribute but it never happened yet...

**Comment by LAAP** [comment]
Hahahah! I see, I will make a "Github workshop" to Markus (@MarkusElKatsha ) so he can contribute to Github

**Comment by agrignard** [comment]
See #114 we have the low, medium and high number and also represented in the color of the agent.

**Comment by LAAP** [comment]
Thank you @agrignard ,

Yes issue #114 is looking fantastic !  Good job!!!
