### ISSUE TITLE
Identify the high risk area

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#120]
(I think that it is easier to measure by time spent in a room by an infected person vs air renovations (ventilation)) Since the simulation probably doesn't have yet the ventilation level, etc. Maybe is number of cases per m2 of room

**Comment by LAAP** [comment]
@agrignard , 

As mentioned in the droplets issue, we can also use the amount of droplets from that part of the model

**Comment by agrignard** [comment]
For now the amount of dropet is acutally directly proportional to the number of people so I am not sure it add anything but let's see

**Comment by LAAP** [comment]
@agrignard , Yes, of course, but  please, use the imagination:

Droplets are cumulative and stays in a space, even when people are moving, so it can be accumulated in indoor rooms, tables, crosspaths, etc, so if they are not cleaned up, that areas became "high-infection areas"

Also, if a person stays long in a place (desk for instance), that desk will accumulate a lot of droplets, so, if it is not cleaned up, next person will deal with all that droplets. so that part of the room has a higher risk level than other parts with people moving and or cleaning

**Comment by agrignard** [comment]
This is issue is now fix and even in a better way that what was discussed.
It will need to be documented as pointed by #142  but we now have 3 types of infection risk that can be displayed just with boolean

`````
	parameter "Draw Infection Grid (only available with SIR):" category: "Risk Visualization" var:draw_infection_grid;
	parameter "Draw Infection by Touching Grid:" category: "Risk Visualization" var:draw_viral_load_by_touching_grid;
	parameter "Draw Viral Load:" category: "Risk Visualization" var:draw_viral_load_per_room;
`````

- draw_infection_grid=> if the SIR is used (which is not the case by default) w can see where the "infection" has been taking place (however this is not realistic as it's very difficutl to know where an infection has taken place but still it's implemented)

- draw_viral_load_by_touching_grid => this will display around the infected people a cell representing the viral load that represent what the infected peple can touch (it's actually not very different from seeing the blue people but as a cell)

- draw_viral_load_per_room=> this one is great as it will show an aggregated value for the room depending on how many infected people are in this room.

We now have this kind of visualization

<img width="735" alt="Screenshot 2020-09-08 at 13 05 15" src="https://user-images.githubusercontent.com/3928502/92469107-8ed66f00-f1d4-11ea-8315-0c095bdfdc6f.png">

By default all those parameters are set to false not to ovrcharge the simualtion but it just need to be set to true to appear. Please feel free to use and explore it by just pressing on this button during the simualtion 
<img width="594" alt="Screenshot 2020-09-08 at 13 11 28" src="https://user-images.githubusercontent.com/3928502/92469275-d5c46480-f1d4-11ea-83b1-6afbb6c8c68c.png">

**Comment by LAAP** [comment]
Dear @agrignard and this is looking Awesome! Good Job!!!
