### ISSUE TITLE
Continous risk infection 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#124]
Right now, as we agreed since a long time top use an SIR model, the infection is in a binary mode you have a certian probability to be infected and ones your are infected you are infected. However some new requirement seems to prefer to have somehow something more "continous" to illustrate the risk of infection.

Woudl it be possible (maybe with keeping the SIR strucutre) to add a risk of infection level that would increase incrementally so we can have something like a gradient form green to red showing the risk of infection.

For now the infection is still by contact but it might also be due later by the fact that you are in a room with lots of droplets, or because you touch a dirty surface or because you did'nt use sanitary point.

**Comment by LAAP** [comment]
@agrignard ,

This could be awesome!

**Comment by ptaillandier** [comment]
Just one question. At the moment we have a SIR model: an uninfected (susceptible) person has a probability of being infected if she/he is close to an infected person. Once infected, she/he can also infect others, which is not realistic.

If we take a continuous model that is more interested in a level of risk, can we not just take into account that at the beginning of the simulation a defined number of people are infected and calculate for each person the risk of being infected. In this case, nobody would become infected during the simulation (to take into account the incubation time), but each person would have a risk factor for being infected (a numerical value).
This would allow scenario comparisons to be made in a more realistic way.

**Comment by agrignard** [comment]
That would be ideal. I think we realize a long time ago that having a SIR for such a short period of time was totaly useless and wrong.That's why we switch to the risk level in the legend but we are still using the SIR to show it

**Comment by LAAP** [comment]
@ptaillandier ,

This is a great idea!!! The numerical value could be the perfect solution for a "infection risk indicator", so agents can shift following a color gradient of "infectioness", and also we could have an aggregated total value of infectioness in the population, and even in the room
