### ISSUE TITLE
Having a boolean for people entering in line or not

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#127]
Would it be possible to have a parameter to trigger if the people wait in line or not before to enter. They would basically not enter in line  in a precovid world and wait in line with the specified distance between people (it might make a biiiiiiiiig line) in the post covid.

We did that for the project in the Champs Elysées but we needed to draw by hand the line, is there a way to do it without drwaing this line? If not we will need to draw in the dxf a new layer represeting the line

**Comment by LAAP** [comment]
@agrignard ,

What about an "offset when waiting", so agents waiting in line, "park" a few pixels away, from the existing "path line already draw in the dxf file "?

**Comment by agrignard** [comment]
@ptaillandier is working on it, let's see what he will produce ;-) We discussed abotu having a parameters defining the time between two people entering in the building (1sec between 2 entrance, 2sec , etc) but he needs to generate programmaticaly the line that doesn't exist on the dxf (it's normal it's not part of the building plan)

**Comment by agrignard** [comment]
It is implemented but not working for #137, #138, 141

**Comment by ptaillandier** [comment]
Now, it works (could be improved, but ok for now).
