### ISSUE TITLE
Possibility to have a shift of scenario to show the cleaning room strategies

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#128]
Right now when a simu representing a scenario (A or B) of an Episode (1,2,3,4, or 5) the simualtion ends.

It could be good to be able to loop on it to represent the shift. It will be very similar to repeat the simualtion but we could have a scenario where we simply loop without cleaning then shit2 arrived in a dirtier place than shit1, etc etc. 

This would show the benefit of cleaning the room

**Comment by LAAP** [comment]
@agrignard ,

This sounds fantastic to me! A loop can help to understand shifts. If we can show also how "dangerous" is to stay in a room more than 45 min due the accumulation of viruses, that could be fantastic

**Comment by agrignard** [comment]
This is also implemented (just need to reinitialize the viral load of a room)

So I don't consider it as an issue, we jsut need to agree on what and how we want to show in the different Episode, but it is technically possible to do that

**Comment by LAAP** [comment]
Awesome @agrignard ,

I reopen this so we can discuss a bit:

I think that we could have a clock or similar where we mark time spent inside of the room and shifts. So in Scenario B we can see rooms getting ventilated and cleaned (infection levels gets reduced) and new or the same agents gets in the room again with less risk. When, in Scenario A, the agents stay and the risk increases during the 3h

Example:
In Scenario A : 0 shifts 3h
In Scenario B : 3 shifts 45min each

**Comment by LAAP** [comment]
Awesome @agrignard ,

I reopen this so we can discuss a bit:

I think that we could have a clock or similar where we mark time spent inside of the room and shifts. So in Scenario B we can see rooms getting ventilated and cleaned (infection levels gets reduced) and new or the same agents gets in the room again with less risk. When, in Scenario A, the agents stay and the risk increases during the 3h

Example:
In Scenario A : 0 shifts 3h
In Scenario B : 3 shifts 45min each
