### ISSUE TITLE
Sanitation point behavior

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#129]
In Episode 3 (see #109) we want to show the sanitation effect.

First we need to have the Sanitation (THIS IS PRETTY URGENT FOR WHOEVER SEE THIS MESSAGE) and then we need to implement the behavior of people that could be something like:

1. A certain amount of peopel goes to Saniation point before to go to the classroms
2. A ceratin amount (that will be defined as a parameter) of people goes to saniataion point during the time spend in the room. This will required a bit of code and change in the behavior of the people are now there movement is trigger by an agenda. I don't think we want to change the agenda concept (just having a kind of subtask while being in the classrroms)

**Comment by LAAP** [comment]
@gamalielpalomo , @milkmonica ,

Please, can you confirm that this is under control?

**Comment by ptaillandier** [comment]
It should work now

**Comment by agrignard** [comment]
it's working but the result are still weird depending on the simualtion, we oftne end up with a worse sanitation than without. 

I reopen it for now just not to forget

**Comment by agrignard** [comment]
There is defintely somethign that needs to be fixe here, in many simualtion the sanitation is worse than the no sanitation... 

Would be fix with #148 (but this one seems difficult to fix)

**Comment by ptaillandier** [comment]
I think it is ok now. I changed 2 things:
- fixe an issue with sanitation usage (... forgotten 'not')
- add a new feature: people who wash their hands will not infect "objects" for a certain period of time.

Seems better now (at least there is an effect).

**Comment by agrignard** [comment]
I reopen this isuse to see if it would ba avilable to work on the line when people goes to the sanitation point. 

According to @ptaillandier theres is already one but it's too smal so maybe it's not a big deal to increase it. Let's see

**Comment by agrignard** [comment]
Maybe a bonus will be to implement a queing effect near the sanitation point

**Comment by LAAP** [comment]
@agrignard queuing and lines are very important as a way of reducing the infection

**Comment by agrignard** [comment]
Queing at sanitation is now here

**Comment by LAAP** [comment]
@agrignard , Can you share an image please?

**Comment by agrignard** [comment]
It's in the simualtion Episode 3_B at some point. You will see it in the video

**Comment by agrignard** [comment]
Something like this 
<img width="740" alt="Screenshot 2020-09-29 at 17 25 05" src="https://user-images.githubusercontent.com/3928502/94579136-c5a22100-0278-11eb-9f68-60794a46629a.png">

**Comment by LAAP** [comment]
Oeoeoeoeh!!!

The line is cool! Congrats!
