### ISSUE TITLE
Common Area behavior 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#130]
For Episode 4 (#110) we want to show what happens in common area. For that we need 

1. To take in account the common area in the simulation and to consider this area a bit differently in this type of area:

- Some people stay at there desk
- Some peopel wander around
- Some people goes from desk to desk

**Comment by LAAP** [comment]
Dear @agrignard ,

This sounds great! Thanks!

**Comment by agrignard** [comment]
@ptaillandier I think the idea is to define a new agenda trying to emulate the behavior of people in a common area like a library. Let me know if this is clear, you can have some freedom here. It's just to avodi that people only stay at there desk like in classrooms (to show that there are a potential high risk infection in this type of space)

**Comment by LAAP** [comment]
Hi @agrignard ,

Yes, this is the idea! Thanks for pushing this into the next level!
