### ISSUE TITLE
Sanitation point in CUAAD

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#131]
@gamalielpalomo , @milkmonica , @LAAP this is getting pretty urgent and is blocking @ptaillandier do implement #129 

Can you please put at least one sanitation point in the dxf?

**Comment by LAAP** [comment]
@gamalielpalomo , @milkmonica ,

Please, can you confirm that this is under control?

**Comment by gamalielpalomo** [comment]
Please see #133, adds sanitation points for CUAAD.

**Comment by agrignard** [comment]
OK great 
<img width="1096" alt="Screenshot 2020-08-28 at 21 37 11" src="https://user-images.githubusercontent.com/3928502/91608922-b9bff800-e976-11ea-8dfa-fe3bf32d5d51.png">
I can see the Sanitation point (in purple here) in the dxf loader, we now need to  implement #129.

**Comment by LAAP** [comment]
Awesome!
