### ISSUE TITLE
Desk layout for CUCEA

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#139]
It seems that there are too many desk for CUCEA no? @milkmonica can you confirm this? 

<img width="855" alt="Screenshot 2020-08-31 at 21 36 52" src="https://user-images.githubusercontent.com/3928502/91759766-82e61e00-ebd2-11ea-9187-c244f34a64f5.png">

**Comment by agrignard** [comment]
is it possible that the chair is made two object? so 2 desks in GAMA? 
<img width="266" alt="Screenshot 2020-08-31 at 21 42 37" src="https://user-images.githubusercontent.com/3928502/91760054-f6882b00-ebd2-11ea-9e35-01b479431d75.png">

**Comment by agrignard** [comment]
For instance this is what Gama produce 
<img width="252" alt="Screenshot 2020-08-31 at 21 48 10" src="https://user-images.githubusercontent.com/3928502/91760475-b83f3b80-ebd3-11ea-87c9-72726b5ebb94.png">
for this
<img width="127" alt="Screenshot 2020-08-31 at 21 48 14" src="https://user-images.githubusercontent.com/3928502/91760522-cab97500-ebd3-11ea-905e-1a01bd3a9ad4.png">

**Comment by agrignard** [comment]
This chair is made of 8 objects...

<img width="252" alt="Screenshot 2020-08-31 at 21 49 36" src="https://user-images.githubusercontent.com/3928502/91760599-e91f7080-ebd3-11ea-8e81-a82581ee030f.png">

**Comment by LAAP** [comment]
@agrignard ,

Here you can find a file with simplified "chairs". I have made "one object" per chair:

I have made a push in github. The name of the file is buildin_L . I didn't want to "overwrite" the old file. Here is the dxf:

https://drive.google.com/file/d/1SH7_hvx4wE1OwksB_3AfAcb1VpJwLjLu/view?usp=sharing

**Comment by agrignard** [comment]
Ok great let me check if it works

**Comment by agrignard** [comment]
Nice thank you master @LAAP ! much more better it reduce to 210 people vs 750...
<img width="724" alt="Screenshot 2020-09-01 at 11 12 13" src="https://user-images.githubusercontent.com/3928502/91831183-0ab84080-ec44-11ea-8426-de5c027def68.png">

**Comment by gamalielpalomo** [comment]
Thank you @LAAP, we also made a dxf to solve this issue yesterday as I said in the last PR, unfurtunately we didnt upload it inmediatly. Whatever, It is good to see this is already working and the issue is closed.

**Comment by LAAP** [comment]
Awesome! Good job team!
