### ISSUE TITLE
Grand Truth graph vs. Simulated graph comparison

### ISSUE THREAD

**Issue by nayoub** [CityScope/CS_Proxymix#14]
@agrignard Save the simulation collision potential graph in a file
@crisjf Compare simulated network with real network

**Comment by agrignard** [comment]
Two graphs are now created and updated in gama
`````
graph<ML_people, ML_people> real_graph;
graph<ML_people, ML_people> simulated_graph;
`````

**Comment by agrignard** [comment]
See https://github.com/gama-platform/gama/issues/2839 for the aggregated spatial graph

**Comment by crisjf** [comment]
@agrignard where are you storing the aggregated simulated spatial graph?

**Comment by agrignard** [comment]
@crisjf you finally have the generated graph. 

Just trigger the saveGrpah tu true when you want to save it, and it create a text file in results/generated_graph.txt

For now I just store 
````
source.username, dest.username
````

Let me knwow if you need another format or other attribute (also easy to change from the code if need in 
````
reflex saveCurrenGraph
````

**Comment by crisjf** [comment]
@agrignard this is great! But to do a better comparison we also need a weight between the agents. Do you think you can also save a simulated "collision potential" for each pair? Based, for example, on the time they spent in close proximity?

**Comment by agrignard** [comment]
right now we just have a connection, the time of the connection is not taken in account (can be good indeed) but it's not implemented yet

**Comment by crisjf** [comment]
We'll have to make do with what we have. Here's how it looks so far. Be aware that as soon as we include the information about the group each person belongs to, the two bars look very much the same.

![image](https://user-images.githubusercontent.com/8973959/68616993-34756080-0494-11ea-97b9-2decb4ede25e.png)

**Comment by crisjf** [comment]
We should generate different versions of the simulated graph with different distance thresholds.

**Comment by agrignard** [comment]
It takes 3 steps ;-)

1. Set the distance 
2. Run the model
3. Save the graph
