### ISSUE TITLE
Better organisation of the model parameters + documentation

### ISSUE THREAD

**Issue by ptaillandier** [CityScope/CS_Proxymix#142]
We are currently in a development phase where we are adding a lot of new features and therefore parameters. Work would be necessary to better arrange these parameters in the code and to document them.

**Comment by agrignard** [comment]
@gamalielpalomo as discussed in one of our meeting, can you  start the documentation process of the project in the Wiki? It will be then used and completed then by your student in the training session.

Here is where you should start
https://github.com/CityScope/CS_Proxymix/wiki/Documentation

**Comment by gamalielpalomo** [comment]
Hi @agrignard and @ptaillandier, I'll begin working in the documentation.

**Comment by agrignard** [comment]
Hi @gamalielpalomo did you find time to work on the documentation? I don't see update on the wiki so far. Let us know how things evolve.

**Comment by agrignard** [comment]
@gamalielpalomo any step on this part?

**Comment by agrignard** [comment]
Seems that this issue is not really active. I close it for now. We are all aware that the model need to be technically documented but we will discussed more in detail who can/want do it
