### ISSUE TITLE
Mask Effect

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#146]
I am not sure that the mask now has the desire effect.

For instance run Episode 1 where the only different is that poeple are not wearing mask or 70% of them are.

We shoudl have a very big difference betwen the 2 scenario in term of high risk but when I run the simualtion the number is very similar.

Maybe something is missing in the way to handle the masK?

@ptaillandier can you have a look at it?

<img width="1530" alt="Screenshot 2020-09-07 at 10 25 20" src="https://user-images.githubusercontent.com/3928502/92365893-bfdf7280-f0f4-11ea-8954-94911b2babe6.png">

**Comment by agrignard** [comment]
Maybe it commes from that change (I didi this change to see more the effect) ? So the effect of the mask is negligeable?

`````
	float indirect_infection_factor<-0.01; //increasement of the viral load of cells per second 
	float basic_viral_decrease_cell <- 0.0001; //decreasement of the viral load of cells per second 
``````
by
``````
	float indirect_infection_factor<-0.5; //increasement of the viral load of cells per second 
	float basic_viral_decrease_cell <- 0.005; //decreasement of the viral load of cells per second 
`````

**Comment by LAAP** [comment]
Hi @agrignard ,

I know that you are just testing the masks, but I want just to remember that in Episode 1 we are testing Masks + Density of people in the room + Time spent.

So Scenario A, No intervention should be with 30 students in the room, and Scenario B should be with 20 students (or less) in the room.

Just for keeping the consistency

**Comment by agrignard** [comment]
Yep, i just wanted to be sure that with the same layout the mask are doing there job (whcih seems to rebe the case after @ptaillandier commit https://github.com/CityScope/CS_Proxymix/commit/3c7e511da11267376ea931dcae7cd535ce668e41) 

I'll check it and close this issue 

However timespent was not very clear in the intial request... (see #107) so it can be here but we just need to agree (the video produced so far is A: No intervention and B:mask+ social distancing. Anyway the time spent is implemented and working so it could be integrated, as always just a question of syncronization...

**Comment by agrignard** [comment]
Ok seems to be fixed (in Episode 1)

**Comment by agrignard** [comment]
MMM I reopen it as i can see sometime that scenario A is worse, i guess we have a stochastic issue here no?

**Comment by agrignard** [comment]
Sorry i did a wrong interpretation of the number. It's coeherent, the number of low risk is lower in the scenario B which makes sense

**Comment by LAAP** [comment]
Hahahaah! Crazy auto-conversation @agrignard ,

Yes, if time (and shifts of new students) can be shown in the videos, that could be fantastic!!!

Also, I have been talking to @milkmonica , and she told me that the UDG is having their own protocols, like 50% of students less than normal, that is 15 students (not 20) instead of 30. So she will clarify in an issue all this protocols so the scenarios can have final fixed numbers.
