### ISSUE TITLE
Problem with dxf Episode 2: 2 objects are created in GAMA

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#150]
@LAAP can you check in the UDG/CUT/lab/building.dxf we shoul have onl one object for the room.

Something is wron gin the dxf  there are 2 of them for the same object

<img width="563" alt="Screenshot 2020-09-09 at 17 16 07" src="https://user-images.githubusercontent.com/3928502/92618052-3bd9e600-f2c0-11ea-94c1-e7ef1286022e.png">

**Comment by LAAP** [comment]
Hi @agrignard ,

I can't see the 2 elements in the dxf. But I have cleaned and closed some vertex. Please, let me know if now works, if not, I will redraw the object

**Comment by agrignard** [comment]
you pushed it in .bak, can you push it in .dxf (AUTOCAD 2013) please?

**Comment by LAAP** [comment]
Hi @agrignard ,

I have pushed also at the dxf. But just in case I have also pushed with a different name: building_L

**Comment by agrignard** [comment]
I don't what you did here ;-)
https://github.com/CityScope/CS_Proxymix/commit/47ce8c0765a6165ee849557d8c5601e312a322cc

it seems that you have added some element in the .gitignore telling not to commit .dxf...

You can try to attached a file though this issue I will fix the gitignore story ;-)

**Comment by agrignard** [comment]
can you retry to pull (toi have the new gitignore) and repull (just the dxf )

**Comment by LAAP** [comment]
I Have an issue
<img width="1244" alt="Captura de pantalla 2020-09-09 a las 12 22 23" src="https://user-images.githubusercontent.com/19315213/92625856-2e5c3600-f297-11ea-9461-ad454f092015.png">

**Comment by LAAP** [comment]
@agrignard Here is the file

[building_L1.dxf.zip](https://github.com/CityScope/CS_Proxymix/files/5196583/building_L1.dxf.zip)

**Comment by agrignard** [comment]
write a commit messsage

**Comment by agrignard** [comment]
Hmmm I am not sure there is a difference between building_L1 and building.dxf

I might check with @ptaillandier why we have 2 room here

**Comment by LAAP** [comment]
Hi @agrignard 
I Have redraw the line. Now, for sure it is only one (it is the only one object in the layer) and it is closed. So it shouldn't be an issue anymore
<img width="1386" alt="Captura de pantalla 2020-09-09 a las 20 00 18" src="https://user-images.githubusercontent.com/19315213/92666427-35a33400-f2d7-11ea-9f2d-a05577542a1b.png">

**Comment by gamalielpalomo** [comment]
@agrignard I am talking with @milkmonica and dont understand wich 2 figures you refer to. Do you refer to the 2 green areas that are shown?

**Comment by agrignard** [comment]
I mention the fact that there are two objects rooms created in GAMA whereas it's only one room. @LAAP redrew it but the problem is still here. I don't why

**Comment by agrignard** [comment]
OK once again thank you @ptaillandier that mange to fix it, however he had to fix it inside Gama as there is apparently still 2 objects... Would be great to be able to have clean dxf (it's clearly out of my knowledge but this format is definetly ... how to say it gently... complicated)!

**Comment by LAAP** [comment]
Thank you @ptaillandier!

@agrignard , As far as I could tell, in the dxf I only see 1 object... So this maybe a UFO kind of challenge. Hahahaha!
