### ISSUE TITLE
Episode 4: Common area type

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#151]
There is something i don't understand in the Episode 4. 

The same object is an Office in scenario A and a common_area in Scenario B and still it seems that people behave like in a common area in sceanario A.

See the picture and the type of the common_area
<img width="1517" alt="Screenshot 2020-09-10 at 09 58 47" src="https://user-images.githubusercontent.com/3928502/92698223-66718080-f34c-11ea-94e7-2ed9cf918620.png">

**Comment by ptaillandier** [comment]
Ok, I fixed the issue with the type of building (not both in scenario A and B, you have a library room). However, I am not sure about the scenarios that you want to explore. 
In both scenarios, are you supposed to have a library and associated behavior (i.e. people moving around the room)?

**Comment by agrignard** [comment]
yes yes like all the episode same site, and differnet parameters, so we whould have the same "environement", maybe I'll play a bit with the ratio between the 2 experiment

**Comment by ptaillandier** [comment]
So, I think it is working normally now

Le jeu. 10 sept. 2020 à 16:50, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Pretty similar shape ;-) 

![13097115](https://user-images.githubusercontent.com/3928502/92753209-f41f9100-f389-11ea-8880-fbe07202adc2.jpg)

**Comment by LAAP** [comment]
Dear @ptaillandier and @agrignard ,

This is looking good. BTW, is the yellow color just indicating the Library? Can we change the color into a Greyish color?

**Comment by agrignard** [comment]
<img width="557" alt="Screenshot 2020-09-11 at 10 06 50" src="https://user-images.githubusercontent.com/3928502/92889447-88373a00-f416-11ea-8ef2-98aee258478b.png">
 @ptaillandier can we make also the libray a Viral room, so we can see how it turn from green to red?

**Comment by LAAP** [comment]
Great idea @ptaillandier !
