### ISSUE TITLE
Problem with timestep change

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#153]
After producing the 5 video I have noticed some strange behavior in time step change (as a results it seems that simualtiona re very long ven if we speed it upo)

For instance 

Run Episode 1_A: peopel are supposed to stay 3h here, at the beginning the time step is equl to one until they arrive in their room, where then it will speed up to 10. However after 45min the time step regoes to 1. I donet understand why (it looks like a 45min is maybe hardcoded somewhere?)

I will also check for the other episode i noticed also some potential improvement

**Comment by ptaillandier** [comment]
I will check, but for the vidéo, you can deactivate it (there is bool
use_change_step or something like that). I already deactivate the
"step-changing" for scenario 4 (common area behavior).

Le lun. 14 sept. 2020 à 11:39, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by ptaillandier** [comment]
ah ah... after rereading your message, I just understood the problem :) .

It's actually a modeling choice: I wanted in multi-simulation that all the simulations remain synchronized (not that on one 3h is passed while on the other, we have just 1h). For that, in multi-simulation, you have to look at what the other simulations are doing to change "step" at the same time.

I can add a global parameter (a boolean) to disable this (each simulation becomes independent from the other for the step definition).

**Comment by agrignard** [comment]
Ok the fact that all the simualtions remain synchronized are great and I think it was someone I request so we can keep it.

What I was refering in this issue is the fact that the acceleration of the timestpe seems to be a weird.

Just to understadn if I want the simualtion being synchronized (the 3h as long as the 45#min) what should I put for bool synchronized_step <- ? true or false?
