### ISSUE TITLE
Better pedestrian path in Episode 2

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#155]
The fact that Episode 2 is just a room implu that there is no pedestrain apth in the room, would it be possible to enhance this?

I am not sure how? could we regenerate the path taking in account the room or the desk to have also a path inside the room?

This is how it looks right now 
<img width="1267" alt="Screenshot 2020-09-18 at 12 35 08" src="https://user-images.githubusercontent.com/3928502/93588351-8f78bd80-f9ab-11ea-8d56-e10f369a08d1.png">

**Comment by LAAP** [comment]
@agrignard , What do you recomend? Do you want to have the drawing of the tables and the path inside the room ? @gamalielpalomo and @milkmonica , can we have this graphos?

**Comment by agrignard** [comment]
Actually would be great to have them as an GIS, that's something we have been discussing for a while (e.g https://github.com/CityScope/CS_Proxymix/issues/81 to geneeate it from GAMA and in many different discussion to produce it by HAnd (it shouldn't be taht difficult). However but I don't know if @gamalielpalomo and @milkmonica have been exploring this path ? (that's one of the main reeason why we have to generate it programmatically) and it will be actually NEEDED in this Episode 5 and really appreciated in others
https://github.com/CityScope/CS_Proxymix/issues/111

**Comment by LAAP** [comment]
Hi @agrignard ,

I think that the path are solved now, isn't it? When I open Qgis I see them:

<img width="1389" alt="Captura de pantalla 2020-09-21 a las 13 18 42" src="https://user-images.githubusercontent.com/19315213/93799375-15e00a00-fc0d-11ea-8eb3-2bbe7a6983ef.png">

It doesn't look like very "fine grain", however, are there. Do you need a more refine grapho?

**Comment by agrignard** [comment]
This one is the one generated by GAMA, so far the 2 Episode run the same one, we will need to create our own educated guess safe path. That can be done though QGIS. If you feel creative and want to do one, you can copy the pedestrain_path and create and commit another one (safe_path.shp for instance). I will have a look also as QGIS can be a bit touchy some time for graph edition.  then I will  implement the loader (which is now taking by default the pedestrian_path.shp)

**Comment by agrignard** [comment]
I close this one for now, as indeed the path exists (could be better) but this is what we have
