### ISSUE TITLE
FINAL DESIGN 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#159]
Here is the current final design (though it's not clear from alst mail from @milkmonica if we keep the text or not). Anyway the case can be remove by the video team as it's not overlerlapping the sites.

So here is the current final one  please fell free to comment/validate/critic

<img width="1498" alt="Screenshot 2020-09-25 at 15 39 03" src="https://user-images.githubusercontent.com/3928502/94273870-45608080-ff45-11ea-8f20-361351c9bf32.png">

**Comment by agrignard** [comment]
Working on some better chart with 100 colored circle
![Uploading Screenshot 2020-09-25 at 17.05.19.png…]()

**Comment by agrignard** [comment]
New iteration with some TriD 
<img width="1501" alt="Screenshot 2020-09-25 at 18 27 53" src="https://user-images.githubusercontent.com/3928502/94292176-e3137a00-ff5c-11ea-86b5-268b3ececc15.png">

**Comment by agrignard** [comment]
Getting  closer and closer to the final design and to the final version of the model also  (only few issues remaining that are not blocking).

Here are the 5 current final Layout also

Unless someone has a good reason to modify the design it will stay as it is. We also have now a powerful dynamic indicator that we made with @tnguyenh that gives a aggregated point of view of the sanitary situation. Also @ptaillandier has spent some time on adjusting Episode by Episode the different paramters to have coherent results (Scenarion B always better than Scenarion B for instance)

As soon as #161 and #162 is close I will regenerate the 10 videos

<img width="1502" alt="Screenshot 2020-09-28 at 11 44 56" src="https://user-images.githubusercontent.com/3928502/94418950-5cd87d00-0182-11eb-8813-e59d04d78870.png">

<img width="1498" alt="Screenshot 2020-09-28 at 11 45 14" src="https://user-images.githubusercontent.com/3928502/94418959-5fd36d80-0182-11eb-8067-61255c3261f4.png">




<img width="1479" alt="Screenshot 2020-09-28 at 11 45 58" src="https://user-images.githubusercontent.com/3928502/94418967-606c0400-0182-11eb-81d6-5203c8004021.png">
<img width="991" alt="Screenshot 2020-09-28 at 11 47 01" src="https://user-images.githubusercontent.com/3928502/94418971-61049a80-0182-11eb-821a-61dd053ab20f.png">
<img width="998" alt="Screenshot 2020-09-28 at 11 47 33" src="https://user-images.githubusercontent.com/3928502/94418973-619d3100-0182-11eb-9a61-992c5f0d0ccc.png">

**Comment by LAAP** [comment]
Hi @agrignard ,

I love @tnguyenh 's dots as an scale of "riskiness". However, I think that we need also to show in a bigger font the numbers of Low, Medium and High Risk population

**Comment by agrignard** [comment]
A proposal (made from photoshop for instance) could help a lot.

**Comment by agrignard** [comment]
What about this? Big enough?
![Uploading Screenshot 2020-09-29 at 13.43.41.png…]()

**Comment by LAAP** [comment]
Hi @agrignard ,

Here are my 2 cents in the design part trying to not change a lot.

A Black version:

![Example1](https://user-images.githubusercontent.com/19315213/94561925-ad0f1800-0232-11eb-9069-ef477af9b518.jpg)

A white version (Quick hack):

![Example1_White](https://user-images.githubusercontent.com/19315213/94561962-b7c9ad00-0232-11eb-8f1f-a5d72b995078.jpg)

Please, let me know your thoughts

Un abrazo!

**Comment by agrignard** [comment]
Ok why not we just spent one day with another world class design that validated the other one. So I guess it's a question of taste... 

I also like this one  just think that with the other one the site/buildign can be bigger as it can take the full width of tje screen no?

**Comment by LAAP** [comment]
@agrignard , If Markus has validated the other one, keep it!

**Comment by LAAP** [comment]
@agrignard , Now I see that the design from Markus fits with all the 5 videos. **So keep Markus**

**Comment by agrignard** [comment]
So here is fro the first Episode . let's see for the other... 
<img width="1211" alt="Screenshot 2020-09-29 at 15 34 27" src="https://user-images.githubusercontent.com/3928502/94565278-4b1dd500-0269-11eb-982f-3a8ee30fd3bb.png">

**Comment by agrignard** [comment]
<img width="1277" alt="Screenshot 2020-09-29 at 15 35 20" src="https://user-images.githubusercontent.com/3928502/94565484-90da9d80-0269-11eb-9cb8-87569d002afa.png">
<img width="1204" alt="Screenshot 2020-09-29 at 15 35 36" src="https://user-images.githubusercontent.com/3928502/94565492-93d58e00-0269-11eb-8612-1096668407ad.png">
<img width="804" alt="Screenshot 2020-09-29 at 15 35 58" src="https://user-images.githubusercontent.com/3928502/94565494-946e2480-0269-11eb-82e1-e86f42293413.png">
<img width="704" alt="Screenshot 2020-09-29 at 15 36 25" src="https://user-images.githubusercontent.com/3928502/94565497-9506bb00-0269-11eb-9d51-3eeb4a3d420b.png">

**Comment by LAAP** [comment]
@agrignard ,

I like this new version... Maybe because it is mine design? Hahahah! Can you push the "time" to the right so it is aligned with the end of the dots line?

**Comment by agrignard** [comment]
Is it your final word ;-) ? 
<img width="1167" alt="Screenshot 2020-09-29 at 15 50 04" src="https://user-images.githubusercontent.com/3928502/94567373-b23c8900-026b-11eb-9aa6-a87c631d8705.png">
<img width="1161" alt="Screenshot 2020-09-29 at 15 50 21" src="https://user-images.githubusercontent.com/3928502/94567383-b49ee300-026b-11eb-9416-098958dc14c8.png">
<img width="1170" alt="Screenshot 2020-09-29 at 15 50 38" src="https://user-images.githubusercontent.com/3928502/94567386-b5377980-026b-11eb-8610-62e5cd7dc2cd.png">
<img width="771" alt="Screenshot 2020-09-29 at 15 51 00" src="https://user-images.githubusercontent.com/3928502/94567389-b5d01000-026b-11eb-8837-ed4c66e72078.png">
<img width="706" alt="Screenshot 2020-09-29 at 15 51 33" src="https://user-images.githubusercontent.com/3928502/94567391-b668a680-026b-11eb-9250-74f1179121d4.png">

**Comment by agrignard** [comment]
From @nayoub input a scale would be nice also

**Comment by agrignard** [comment]
Also the yellow circle are too big

**Comment by agrignard** [comment]
Add the scale at the bottom left 

<img width="1199" alt="Screenshot 2020-09-29 at 17 21 56" src="https://user-images.githubusercontent.com/3928502/94578869-7fe55880-0278-11eb-84dc-959092b4fb81.png">
<img width="1203" alt="Screenshot 2020-09-29 at 17 22 21" src="https://user-images.githubusercontent.com/3928502/94578877-807def00-0278-11eb-8faf-486a5d30cb9a.png">
<img width="820" alt="Screenshot 2020-09-29 at 17 22 51" src="https://user-images.githubusercontent.com/3928502/94578880-81168580-0278-11eb-9b5f-0759a2265cae.png">

**Comment by agrignard** [comment]
I will froze this design to generate the 10 videos today

**Comment by milkmonica** [comment]
Hello everyone, first of all thank you for all the excellent work you have done!, especially in these moments that Gama and i have complicated delivery times. 
thank you very much also for making decisions not to stop the flow, excellent decisions too! I showed them to social communication and now the information can be read very clearly!
Regarding the final decision for these design issues, the black layout seems good to them and also to keep the text as it now appears, the only thing they comment that it would be good to change, is that the blue color is not clearly visible on the black background, and that it would be better to use a shade of blue that has better contrast.

**Comment by nayoub** [comment]
Hi everyone, here's a first quick proposal for the layout @agrignard 
Let me know what you think ;)
![Proxymix COVID-19 Copy 4](https://user-images.githubusercontent.com/49419303/94607061-6b4d9400-0269-11eb-8d0d-5ba8e4954c32.png)

Color used (RGB):
Blue: 50, 197, 255
Green: 109, 212, 0
Orange: 247, 181, 0
Red: 244, 67, 54

**Comment by agrignard** [comment]
@nayoub great design for a "squared shape site", what woudl you propose for this one which is very "large". If I keep the same text layout I am afraid the site will look very small

<img width="1466" alt="Screenshot 2020-09-30 at 12 14 58" src="https://user-images.githubusercontent.com/3928502/94673190-ab1e8500-0316-11eb-81af-d62ea6475959.png">

**Comment by agrignard** [comment]
One first iteration in GAMA after a looooooong night with @tnguyenh to implement the new dynamic sliders!

Works pretty well for Episode 4 and any square environment 
<img width="1481" alt="Screenshot 2020-09-30 at 13 14 26" src="https://user-images.githubusercontent.com/3928502/94678585-0b192980-031f-11eb-8385-8c08bd1e1603.png">


but it's still problematci for the Episode 1
<img width="1608" alt="Screenshot 2020-09-30 at 13 15 19" src="https://user-images.githubusercontent.com/3928502/94678637-1b310900-031f-11eb-87eb-2416549c3ca5.png">

**Comment by nayoub** [comment]
Very cool!! Bravo @agrignard + @tnguyenh!
I’ll try to find something for a very long one (episode 1)

________________________________

**Comment by agrignard** [comment]
And what if we jsut place this long buildign in the middle? To do so maybe it could be useful to have an invisible frame arounf it in the dxf. That would make the preocess much more easier

@nayoub can you try to add an invisible frame with a "normal ratio" around it just to see if it works?

**Comment by LAAP** [comment]
Wow!!! good Job to @all , especially to @agrignard + @tnguyenh 

It is there!

**Comment by agrignard** [comment]
Yep almost there, the very not funny part now is to have it working for each Episode...

For next project let's be sure we have 5 sites with the same ratio it will save a looooooooooooooooooot of time....

**Comment by LAAP** [comment]
@agrignard ,

We will always have very different ratios. I think we need to find a smart way of escalating everything for the different ratios, so then, we will have the generic perfect tool for Architects    ;)

**Comment by agrignard** [comment]
OK so thanks to this Amazing building that we chose in the first scenario it's just impossible to have something generic (I love architects!)

So here are the 2,3,4 and 5 design and @nayoub and I will work on a specific one for Episode 1 (@nayoub can you push it here ones it's done)

<img width="1503" alt="Screenshot 2020-09-30 at 18 20 20" src="https://user-images.githubusercontent.com/3928502/94712881-5c8ade00-034a-11eb-8006-89b86b4cebfc.png">
<img width="1707" alt="Screenshot 2020-09-30 at 18 20 57" src="https://user-images.githubusercontent.com/3928502/94712889-5eed3800-034a-11eb-901a-ee63d674eb7a.png">
<img width="1462" alt="Screenshot 2020-09-30 at 18 21 23" src="https://user-images.githubusercontent.com/3928502/94712894-601e6500-034a-11eb-94ee-4e610dba2f4a.png">
<img width="1335" alt="Screenshot 2020-09-30 at 18 24 05" src="https://user-images.githubusercontent.com/3928502/94712896-60b6fb80-034a-11eb-8d8d-56f47f535309.png">

**Comment by LAAP** [comment]
Yep. Building 1 is not looking good... However, the other scenarios are very good

**Comment by agrignard** [comment]
For the Guadalajara project the final design is done
