### ISSUE TITLE
Separate render in separated files of text and building for episodes

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Proxymix#160]
Hi @agrignard ,

@milkmonica is asking about rendering the scenarios with the text in one video and the agents and buildings in a separated one:

_"the only thing that requires the department of UDG social communication is that all the elements are given separately (simulation of space separated from text) to make decisions about the general composition. "_

Also, maybe we will have feedback regarding the RGB colors:

_"Throughout the day she will tell me if they require the change of some colors in the representation of the simulated space (based on RGB)"_

**Comment by agrignard** [comment]
This is clearly not possible from GAMA and not what was intially plan so it won't be done,
However it shoudln't be difficult from any post-production software as the 2 information are not overlapping

**Comment by LAAP** [comment]
Mmmmmm. OK, Maybe I can suggest them to do it from Premier. Hahahaahah! Just with a "black mask" Hiding the text and other hiding the building

**Comment by agrignard** [comment]
This is a post production issue that won't be fix here. I personally think (especially when we see the time we ha
ve spent on it) that we should keep our design (see #159) instead of recreating a new one. If there is a new one we need validate it before to releas it. Also as I already explained the number are dynamic so need to be in sync with the simulation.

**Comment by milkmonica** [comment]
Thank you both very much!
What happened is that we all took a course with Gama and he show us how to change RGB values in all agents, that stuck in our minds and we thought about it as an adjustment possibility for UDG colors, we all understand that this can also be done in any other video editor, but the idea was not to correct the originals if from base it could already be adequate with, we understand that the delays have been many and for now we must all concentrate our efforts on closing this project! :D
So now everyone in social communication agrees that the layout they have configured is maintained.

Anyway, as I answered in the issue of the final design, social communication will be in charge of editing it, the only mention is to change the blue color to a tone that is not lost with the black background and everything would be ready for this final phase.

**Comment by LAAP** [comment]
Thank you @milkmonica , @agrignard and @tnguyenh are working the RGB palette, and we are planning to have a final cut for tomorrow
