### ISSUE TITLE
Episode 4

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#161]
Be sure that all the infected people goes in the same room. right now it both scenarios it's not excatly the same so some time Episode B is wrose Episode A

And potienally too much people "rase les murs"

@ptaillandier will check the init

**Comment by LAAP** [comment]
@agrignard , Why all infected people should go to the same room?

I think that if we reduce density of people, Keep distance, reduce time in the room, and where masks. That should be enough to reduce the risk. Isn't it?

**Comment by agrignard** [comment]
In the same room between the 2 scenario

**Comment by agrignard** [comment]
Ok we are good for this one also
