### ISSUE TITLE
Room blending color

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#163]
Now that we are in the real design part (see #159) it's not possible to keep the color room as it is. The color goes from Green to brownish to Red it really looks really ugly.

So for now the color of the room has been disabled to have a coherent design and we will work on it with @tnguyenh and @nayoub to have a better way to interpolate color between "nice" color.

**Comment by nayoub** [comment]
Here's an option for the color palette, following our discussion on the phone ;)

RGB codes (from green to orange to red):
109, 112, 0 (low-risk)
175, 190, 49
211, 186, 25
247, 181, 0 (medium-risk)
246, 143, 18
245, 105, 36
244, 67, 54 (high-risk)


![Palette_ProximixUDG](https://user-images.githubusercontent.com/49419303/94743280-1b43ff80-0345-11eb-84d4-4cabde999b15.png)

**Comment by agrignard** [comment]
Nice! Let me integrate this in the room and see how it looks

**Comment by LAAP** [comment]
This color palette is fantastic for the agents. @agrignard , maybe @nayoub , can make lighter palette one for the background (that respect the agents, but it is solid), in the same way that we have this for the agents, so we do not need to give transparency to the color. What do you think?

**Comment by agrignard** [comment]
Due to the very diffeetn viral load for each episode it's not that straightforward to use this palette (though it looks great). So the calssi blen from green to red has been chose for the final episode

**Comment by nayoub** [comment]
True... it also depends on your screen etc so quite complex to caliber

________________________________

**Comment by LAAP** [comment]
Yes, crazy complex...

**Comment by agrignard** [comment]
No it shouldn't be that complex but it is how it is
