### ISSUE TITLE
Episode 5 ending

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#165]
At the very end of the Episode 5, when people goes out of the campus they do not follow the path, whch makes a wei
rd effect .

@ptaillandier any chance to have a look? Maybe reduce a lot the density to make it faster

<img width="727" alt="Screenshot 2020-10-02 at 12 00 57" src="https://user-images.githubusercontent.com/3928502/94911830-01bac900-04a7-11eb-8444-961e0d5131b8.png">

**Comment by LAAP** [comment]
@agrignard , Maybe we can also give 3 to 4m distance between people. In the campus, people have more space than indoor.

Density of Scenario B should be half of Scenario A, the should have masks, and spend less time in the campus

**Comment by agrignard** [comment]
THis episode is way to complex and not meaningful regarding the number of people. We won't fix this right now
