### ISSUE TITLE
ABM keeping distance between agents for all the escenarios-A (traffic example)

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Proxymix#167]
Hi @agrignard 

What about implementing something simple, not rocket science, to have the agents keeping the "social distance" between of them. Here there are several examples:

[**Article-1:**](https://www.researchgate.net/publication/261379704_Traffic_simulation_using_agent-based_models)

_"The   method   Car::tick()   determines   the   behavior   of   a   car
within simulation at each tick. It can be described with the
following pseudocode:
attempt_changing_lanes;
if (at_intersection) decide_new_directon;
if (semaphore==red||semaphore==yellow) stop;
else if (distance_from_other_vehicle<ideal*K)
speed -= k1;
else speed += k2;
do_move;
if (at_finish) self_destruct;
Function  attempt_changing_lanes  decides "_ 

[**Article-2:**](https://www.scirp.org/journal/paperinformation.aspx?paperid=84738) The AnyLogic example  ;)

[**Article-3:**](https://www.researchgate.net/publication/329883797_Building_composing_and_experimenting_complex_spatial_models_with_the_GAMA_platform) Wow! Gama team has also an article!!!

[**Article-4:**](https://hal.archives-ouvertes.fr/hal-01055567/document) Patric has his own article!   ;)

**Comment by agrignard** [comment]
Long term issue. I close it for now as it won't be implemented in the current version
