### ISSUE TITLE
Multi Infection Risk Factor

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#168]
In a next step mood It would be nice to differentiate 3 types of infection risk

- Direct infection risk
- Air Infection risk 
- Object infection risk

Right now the 3 process are of course take in account separately but they update a global infection risk parameters. 

With 3 different indicator we can have some interesting plot that shoes the direct benefit or not at the people level of the intervention

**Comment by LAAP** [comment]
@agrignard , This is a great idea! Can we have a health care specialist for start "validating" this models with experts?

**Comment by tnguyenh** [comment]
There can be two kind of charts: time series showing the average viral load per person for each mean of contamination, and a pie chart showing the relative contribution of each mean of contamination.

I'm not sure that reliable quantitative data exist, however it would be nice if it could be validated somehow.

**Comment by LAAP** [comment]
Hi @tnguyenh and @agrignard ,

Can we contact the team of pandemic experts that helped Alexis?

**Comment by agrignard** [comment]
This is now implemented and has rised #169
