### ISSUE TITLE
Infection risk analysis

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#171]
Right now we are giving the number of people with low, med and high risk and showing the cumulative infection for direct , object and air like this
<img width="708" alt="Screenshot 2020-10-21 at 10 45 51" src="https://user-images.githubusercontent.com/3928502/96696133-b6e7ef00-138a-11eb-867c-865d5cd6e51c.png">

What could be another good way to analyse visually with chart the infection risk?

**Comment by agrignard** [comment]
New version with histogram per infection risk
<img width="1726" alt="Screenshot 2020-10-21 at 11 12 10" src="https://user-images.githubusercontent.com/3928502/96699211-4e027600-138e-11eb-8224-5b7b1a005f4e.png">

**Comment by LAAP** [comment]
@agrignard This is fantastic!

**Comment by agrignard** [comment]
See the paper written for MABS 2021/ AAMAS
