### ISSUE TITLE
Wrong formula for fomites

### ISSUE THREAD

**Issue by tnguyenh** [CityScope/CS_Proxymix#178]
Lines 252-258, replace by

````reflex infection_by_fomite when:not target.not_yet_active and not target.end_of_day and  fomite_infection and not is_infected and not target.is_outside and not target.using_sanitation {
		list<fomitableSurface> fS <- (fomitableSurfaces) overlapping self;
ask fS{
	myself.cumulated_viral_load[1] <- myself.cumulated_viral_load[1] + hand_to_mouth  *((myself.has_mask? (1-fomite_mask_reception_efficiency) : 1) * self.viral_load* (1-(1-proportion_of_fomite_viral_load_transmission_per_second)^step));
	do remove_viral_load(self.viral_load* (1-(1-proportion_of_fomite_viral_load_transmission_per_second)^step));	
	}
}
````

where proportion_of_fomite_viral_load_transmission_per_second is a parameter between 0 and1 which gives the proportion of virus transmitted to the hands per time unit.

Line 236, replace

````do add_viral_load((myself.has_mask ? fomite_mask_emmision_efficiency : 1 )* viral_load_to_fomite_infection_per_time_unit * step);````

by

````do add_viral_load((myself.has_mask ? (1-fomite_mask_emmision_efficiency) : 1 )* viral_load_to_fomite_infection_per_time_unit * step);````

**Comment by tnguyenh** [comment]
Actually the previous formulas (* step and not ^step) work but they are approximations that work ONLY if step is small.

**Comment by agrignard** [comment]
Potentially fixed but blindly
