### ISSUE TITLE
Problem with dxf visualization

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#187]
Run Models/ToolKit/DXF_Validator.gaml

This model use to validate the existing and missing layer and was then displaying the dxf element.

However now the dxf element are not drawn

<img width="1440" alt="Screenshot 2021-09-29 at 10 50 28" src="https://user-images.githubusercontent.com/3928502/135235694-b7b140c5-9ece-47bc-84ef-5ae45d4e69f5.png">

**Comment by ptaillandier** [comment]
it is due to the fact that the background is black and you draw the elements in black...

**Comment by agrignard** [comment]
Sorry my bad...
