### ISSUE TITLE
Cannot run pedestrian model

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#19]
@ptaillandier should I Use a specific version of GAMA 

With GAMA 1.8 and the install plugin I have the following error, if possible I woudl prefer this model to be compatible with GAMA 1.8 

list<geometry> pp <- generate_pedestrian_network([StructuralElement], [world],false,false,3.0,0.1, true,0.1,0.0,0.0,50.0);

``````
No operator found for applying 'generate_pedestrian_network'
   to types [list, list, bool, bool, float, float, bool, float,
   float, float, float] (operators available for [types [list,
   string], types [list, string, float, float, float, bool, float,
   float, bool, bool]])
```````

**Comment by agrignard** [comment]
@ptaillandier it is still not working with the last version of GAMA and the last plugin version

What do I miss here? 
<img width="1042" alt="Screen Shot 2020-03-15 at 13 59 00" src="https://user-images.githubusercontent.com/3928502/76707384-2d21c600-66c5-11ea-8b8b-4ee59a22677b.png">

**Comment by ptaillandier** [comment]
You can update the plugin and it should work (Help menu -> check for
updates, just select the pedestrian plugin).

Le dim. 15 mars 2020 à 18:59, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
OK it compiles when I updated the plugin; however, the experiment generatepedestrinnetwork doesn't ' work producing this error

``````
2 occurrences in 2 agents at cycle 0: Java error: StackOverflowError
in list<geometry> pp <- generate_pedestrian_network([StructuralElement],[world],false,false,3.0,0.1,true,0.1,0.0,0.0,50.0);
StackOverflowError: null
escape.gaml.operator.Operators.generateNetwork(Operators.java:81)
escape.gaml.operator.Operators.generateNetwork(Operators.java:81)
escape.gaml.operator.Operators.generateNetwork(Operators.java:81)
escape.gaml.operator.Operators.generateNetwork(Operators.java:81)
escape.gaml.operator.Operators.generateNetwork(Operators.java:81)
escape.gaml.operator.Operators.generateNetwork(Operators.java:81)
escape.gaml.operator.Operators.generateNetwork(Operators.java:81)

`````
