### ISSUE TITLE
Level 0 CAD Office to Offices

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#191]
<img width="580" alt="Screenshot 2021-10-19 at 20 39 06" src="https://user-images.githubusercontent.com/3928502/137970996-7de60dc5-6f2d-477a-b770-a5055fef8746.png">

@LAAP can you change Office by Offices like in the working CAD

Please update directly this file 
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/IDB/Level%200/building.dxf

**Comment by LAAP** [comment]
Solved Now you have the fils "Mesa_Redonda_X_X.dxf" files with the renamed and fixed names
