### ISSUE TITLE
Track individual contagion

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#20]
Right now the infection happens with a certain probability if some infected people are in your neighborhood

`````
     reflex become_infected_by_direct_contact when: (is_susceptible and cycle mod infectionUpdateTime = 0){
    	float rate  <- 0.0;
    	//computation of the infection according to the possibility of the disease to spread locally or not
    		int nb_hosts  <- 0;
    		int nb_hosts_infected  <- 0;
    		loop hst over: (people at_distance socialDistance) {
    			nb_hosts <- nb_hosts + 1;
    			if (hst.is_infected) {
    				nb_hosts_infected <- nb_hosts_infected + 1;
    			}
    			
    		}
    		if(nb_hosts!=0){
    		  rate <- nb_hosts_infected / (nb_hosts);	
    		}else{
    			rate<-0.0;
    		}
    		

    	if (flip(beta * rate)) {
        	is_susceptible <-  false;
            is_infected <-  true;
            is_immune <-  false;
            color <-  #red;    
        }
    }
``````

then it's impossible to keep track of who exactly gave you the virus, do we want to keep ot like this or be able to track who has really gave the virus (even if indeed if two infected are in yoru circle how can you knwo who gave it to you

@tnguyenh what do you think?

**Comment by RELNO** [comment]
Without knowing the current logic (maybe good to talk this through),the way I’d approach this is via object prop inheritance: 

if O (object) is infected:
    if O is < d (distance) from O` (2nd object) (vertical or horizontal) for more than  t (time):
        if O is human: 
                  O is infected for t + 6 weeks
       else
                  O is infected/infecting for t + (whatever the max time of surface diffusion)

**Comment by tnguyenh** [comment]
In my opinion it is not relevant to know who transmitted the disease. There is no way to do so in reality. For contaminated surface, you can find a mix pool of virus. It is not common to actually consider that a contamination is due to a single virus. Contamination happens when the viral load is above a kind of threshold. So tracking transmission in that kind of disease is not really relevant.

**Comment by agrignard** [comment]
I will create a mirror species that will take care of running on SIR model on top of the population and potentially having people infecting specific places that they are touching.

**Comment by agrignard** [comment]
fixed since a long time ago
