### ISSUE TITLE
Naming convention for layer

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#21]
In order to have a generic framework, it will be necessary to agree on a standardization for the layer name.

So far this is more or less what we have 
````
"Offices","Elevators","Meeting rooms","Coffee","Stairs","Storage","Toilets","Walls","Supermarket"
``````

However this is list is 1. will evolve and 2. not using a real standard.

@nayoub  do you nay standard in the architectural world that we could use ?

**Comment by nayoub** [comment]
There is no real standard, the best would be to define our own standard.
