### ISSUE TITLE
Problem with spatial unity of DXF file

### ISSUE THREAD

**Issue by ptaillandier** [CityScope/CS_Proxymix#22]
In the current version, the unit used to import DXF files is the meter, but this seems odd considering the size of the building. It would be worth correcting the unit (is the unit used in the DXF files the centimeters, the feet, other?).

**Comment by nayoub** [comment]
The DXF file is in centimeters, as was the original Media Lab one. But it worked fine on the initial Proxymix, no?
I can change the units to meter if you want, let me know.

**Comment by ptaillandier** [comment]
No need to modify the dxf files, just to specify the right units in GAMA
(I'll take care of it)

Le mer. 1 avr. 2020 à 17:16, Nicolas Ayoub <notifications@github.com> a
écrit :
