### ISSUE TITLE
DXF import in Gama is reversed

### ISSUE THREAD

**Issue by nayoub** [CityScope/CS_Proxymix#24]
When I import the DXF file in Gama, it appears reversed so I always manually reverse it on CAD to have it in the right Z direction on Gama. Have you notice this or is it just my computer?

**Comment by agrignard** [comment]
Yes you're right the model is flipped down (however on GAMA it's on the y-axis not the z), and it comes from a convention that are indeed different depending on the software used. The GAMA convention is the same as the OpenGl one. However, we might report this issue on Gama Platform to fix it.
