### ISSUE TITLE
Integrate Lyon Floor Plan

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#28]
Welcome to @cocsfav AND @pacopaco74 that are joining the Proximyx force and will help to have something running in public space in Lyon.

So far we will have Hotel-Dieu, ENSAL, and Learning center.

The dxf file is loaded correctly in the DXF_File Import; we now need to have our COVID model running on it.

To do so the dxf file needs to have very specific layer name to be able to initiate correctly the model.

So far this model was run for the 3rd floor of the media lab with a very basic behavior. It can be run assuming that we have the following layer:
`````
["Offices","Meeting rooms","Entrance"::#yellow,"Elevators","Coffee","Supermarket","Storage","Furnitures","Toilets","Toilets_Details","Walls","Doors","Stairs","Path"];
`````

First step @pacopaco74 and @cocsfav can you change the name fo the layer in your dxf file to be sure to have all of them. Then we might have to modify a bit this list if you think there is some specific room missing.

The idea is to have a generic model that can be applied to any public space, but for that we need to agree all together about what make a public space (the list of possible and mandatory layers to run the ABM model)

**Comment by pacopaco74** [comment]
In my last commit ( 8314b6b ) I changed the name of the layers in the ENSAL-RDC DXF files to match the ones required for the COVID model : ["Offices","Meeting rooms","Entrance"::#yellow,"Elevators","Coffee","Supermarket","Storage","Furnitures","Toilets","Toilets_Details","Walls","Doors","Stairs","Path"];
I had create 3 additional ones specific to ENSAL : ["Classrooms","Terrace","Library"];
However, a bug appeared when I tried to run the new DXF in Gama :
<img width="1792" alt="Capture d’écran 2020-05-15 à 20 28 24" src="https://user-images.githubusercontent.com/60396205/82083868-aa2fe280-96ea-11ea-9468-5ebebe8935ab.png">

**Comment by agrignard** [comment]
Maybe there is a problem in the additional shapes. I would suggest to do this step by step and check at every step that GAMA can read the file.1. to start from the one that works 2. modify the existing layer name, 3. Add the additional ones (and process iteratively until having something that works.

**Comment by cocsfav** [comment]
In my last commit, I changed the name of the layers in the Grand-Hotel-Dieu_Lyon DXF file to match the ones required for the COVID model : ["Offices","Meeting rooms","Entrance","Elevators","Coffee","Supermarket","Storage","Furnitures","Toilets","Toilets_Details","Walls","Doors","Stairs","Path"];
I had to create 2 additional ones specific to ENSAL : ["Outdoor spaces","Restaurants"];

**Comment by agrignard** [comment]
OK great! So i see it's working in DXF File Import however there is an issue to run the COVID model. I'll create a dedicated issue

**Comment by agrignard** [comment]
I close this issue for more specific ones
