### ISSUE TITLE
ENSAL DXF Not Compatible 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#31]
@cocsfav and @pacopaco74 there is an issue with the 2 ENSAL file. It's not working on 1.8, it is working on the last version of GAMA thanks to @ptaillandier fix, but it would be great to have it working on 1.8

Would you be able to see what's the difference between the Hotel Dieu and ENSAL? According to @ptaillandier one of the issues might come from something related to font?

Let me know what you think, and also maybe the file is a bit too complex, for a first iteration something a bit simpler might help (and only one floor should be fine too)

**Comment by ptaillandier** [comment]
To be more specific, it seems to be due to the use of "\A1{\". I'm not at
all familiar with the dxf format, but it's a priori a tag used for text
formatting (
https://www.cadforum.cz/cadforum_en/text-formatting-codes-in-mtext-objects-tip8640
).

Le ven. 22 mai 2020 à 11:38, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by pacopaco74** [comment]
Ok thanks for the insights I'll check it out

**Comment by agrignard** [comment]
@cocsfav maybe you can have a look at this one now that you are getting an expert ;-)?

**Comment by agrignard** [comment]
I Have change a bit the expermient name

I have put this experiment ````DXFWorkInProgress````for the current DXF that doesn't work

So you can run this one to check the ENSAL one. For the other experiemen tI just keep the dxf that are currently working

**Comment by cocsfav** [comment]
Okay, I'll take a look.

**Comment by agrignard** [comment]
I Just did a last change so in ToolKit now you have the DXF Validator that shoes the current valid one when running ````ValidatedDXF````` (Standard Factory, MediaLan, Hotel Dieu)
<img width="1920" alt="Screenshot 2020-05-25 at 12 35 13" src="https://user-images.githubusercontent.com/3928502/82805457-5a88ae00-9e84-11ea-94c5-e28c447f7fb2.png">

And `````WorkInProgressDXF```` for ENSAL and Learning Center

**Comment by cocsfav** [comment]
@agrignard I hope I did not do anything stupid, I merged something in the master branch...
The DXF file of ENSAL-RDC is working.

**Comment by agrignard** [comment]
ouch, there has been something wrong in the last commit... most of the change from this morning are lost...

Do you remember what you did?

**Comment by cocsfav** [comment]
I'm really sorry I had a problem with my Github app...
I think that I commited all the modifications I did

**Comment by agrignard** [comment]
Yes it's a bit a mess indeed ;-) So for now I think we will go back to  the Pull Request to avoid this.

**Comment by cocsfav** [comment]
Sorry for my mistake Arnaud... Is there a way to remove a commit?

**Comment by agrignard** [comment]
Ok no worries I fixed it (I reput the last version I pused for the code but then I am not sure abotu the dxf). it can happen gitHub Desktop is a bit tricky sometimes (just be sure to try as much as possible to pull before to commit and if you have a doubt on something then create a branch and make a PR instead.

**Comment by agrignard** [comment]
Ok so I can see ENSAL-RDC in the DXF_Validator however in the COVID simu it seems pretty heavy. I close this issue and create a more specific ones.
