### ISSUE TITLE
Problem with Grand-Hotel-Dieu_Lyon unity (#cm vs #m)

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#33]
This how look the "Grand-Hotel-Dieu_Lyon" model (it's working so it's a ggod news but there is something weird with the unity

<img width="850" alt="Screenshot 2020-05-22 at 12 26 17" src="https://user-images.githubusercontent.com/3928502/82658541-74798500-9c27-11ea-860e-87ba015c9c0f.png">

@cocsfav and @pacopaco74 can you chekc the unity of the Grand-Hotel-Dieu_Lyon. 

Also I don't know how to check the unit of a dxf file? Are you doing it with Autocad? Ideally, we should agree on the good one( I have the feeling that #cm is used for the MediaLab original project)

@nayoub any though on that?

**Comment by cocsfav** [comment]
@agrignard I just found the error by opening my file on Gama, I correct the problem and I put the dxf online.

**Comment by agrignard** [comment]
OK great can you commit and push file?

**Comment by cocsfav** [comment]
I just pushed file. Did it work?

**Comment by agrignard** [comment]
No it's not appearing in the list of commit in the master

https://github.com/CityScope/CS_Proxymix/commits/master

You have first to commit and then push (then you can see if you see it on the website here
https://github.com/CityScope/CS_Proxymix/commits/master)

**Comment by cocsfav** [comment]
Thanks, now it is OK normally.

**Comment by agrignard** [comment]
Ok it's getting better but still it seems that the unit is wrong (the legend said 2m for something which I think is bigger). The dot are still pretty big
<img width="1325" alt="Screenshot 2020-05-25 at 11 41 59" src="https://user-images.githubusercontent.com/3928502/82800943-cf57ea00-9e7c-11ea-84bf-b4fa4150d5d4.png">

**Comment by agrignard** [comment]
Yes looks much more better! Good job!

I let you clsoe your first issue?

**Comment by cocsfav** [comment]
I just commited the final version of the DXF file. Now it's working : 
![20200525_Grand-Hotel-Dieu_Lyon_Capture](https://user-images.githubusercontent.com/64479147/82801368-7e94c100-9e7d-11ea-839d-bbd88cf9c0b7.JPG)

**Comment by agrignard** [comment]
Yes I see that 's perfect. So I close this issue as the model is now compatible (of course still need some work but the dxf is valide so it's a great step)
