### ISSUE TITLE
DXF Validator

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#34]
I am thinking of a good way to know if the dxf provides is valid or not to later run the ABM on it.

For now, I consider a dxf validate if and only if it has at least all the following elements (at least ones)

	["Offices"::#blue,"Meeting rooms"::#darkblue,
	"Entrance"::#yellow,"Elevators"::#orange,
	"Coffee"::#green,"Supermarket"::#darkgreen,
	"Storage"::#brown, "Furnitures"::#maroon, 
	"Toilets"::#purple,  
	"Walls"::#gray, "Doors"::#lightgray,
	"Stairs"::#white];

@ptaillandier what would be an easy syntax in GAML to be sure that at least one agent is one of this type?

**Comment by ptaillandier** [comment]
Which of these types are mandatory and which are optional?
I mean, "Stairs" is mandatory or not? and "Coffee" ?

**Comment by agrignard** [comment]
So this list might evolve and actually you're right we could have mandatory and optional elements

It will aslo depends on the type of building (uinversity, factory, train station, public spaces)

But for now we have only one model (COVID) running  the mandatory or optional actually depends on the ABM running so for now according to the code those elements are mandatory ("Walls","Entrance", "Offices", "Supermarket", "Meeting rooms","Coffee","Storage")

the rest is optional or anything else woudl be useless

`````
			if (type = "Walls") {
				create wall with: [shape::clean(polygon(se.points))];
			} else if type = "Entrance" {
				create building_entrance  with: [shape::polygon(se.points), type::type] {
					do intialization;
				}
			} else if type in ["Offices", "Supermarket", "Meeting rooms","Coffee","Storage"] {
				create room with: [shape::polygon(se.points), type::type] {
					do intialization;
					
				}
				
			}
``````

**Comment by ptaillandier** [comment]
Done...; but for the moment, we have just an error message in case of
missing layers.

Le lun. 25 mai 2020 à 11:15, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Ok great thank you!  I will move it in the DXF validator (that will then be imported)

**Comment by agrignard** [comment]
Can we also add the unnessecary elements? In sime case thre are lot of them

**Comment by agrignard** [comment]
Ok done in
https://github.com/CityScope/CS_Proxymix/commit/d607c62e51932a1549fc916e6121e67e7627d32e

IS there a way to throw a warning instead of an error for the optional?

**Comment by ptaillandier** [comment]
done for the useless layers

you can send a message (do tell) instead of an error (do error)

Le lun. 25 mai 2020 à 11:34, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Perfect! Thank you
