### ISSUE TITLE
Remove big Wall in Hotel Dieu

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#35]
It seems that the Floor is labelize as the wall @cocsfav do you think you can just change the label of this layer to floors?
<img width="1096" alt="Screenshot 2020-05-25 at 12 07 12" src="https://user-images.githubusercontent.com/3928502/82803161-565a9180-9e80-11ea-80e9-6484365fa1b3.png">

**Comment by cocsfav** [comment]
Ok, I'll fix it.

**Comment by cocsfav** [comment]
I changed the big wall in Floor. Is it better now ?

**Comment by agrignard** [comment]
Yes!
