### ISSUE TITLE
Lyon Learning Center

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#36]
@pacopaco74 I notify something wrong in the learning center layer name that we were using in Lyon in February,

<img width="555" alt="Screenshot 2020-05-25 at 12 10 18" src="https://user-images.githubusercontent.com/3928502/82803472-e26cb900-9e80-11ea-8f59-910564fefea7.png">

Do you think you can update those layer name so that they are compatible with the new nomenclature that can be found here

**Comment by pacopaco74** [comment]
Normally fixed it in my last commit : d223086

**Comment by agrignard** [comment]
OK great!

Now the dxf is missing some layer to be able to have the ABM model running on top of it.

I wll create the mandatory field soon but I think it's something like

"Walls", "Entrance","Offices", "Supermarket", "Meeting rooms","Coffee","Storage"

So far there is no entance right?

**Comment by pacopaco74** [comment]
Didn't quite understand, are those the one that are mandatory to be able to run the ABM model?
"Walls", "Entrance","Offices", "Supermarket", "Meeting rooms","Coffee","Storage"
 
I will add an "Entrance" layer to the DXF and change the Actual "Classroom" layer by "Meeting rooms"

**Comment by pacopaco74** [comment]
Also, I remember you told something in a previous issue about being able to define the layers that are common to every building, and the one that can be added later on ?

**Comment by agrignard** [comment]
"Walls", "Entrance","Offices", "Supermarket", "Meeting rooms","Coffee","Storage"=> yes however you can have a coffee and no storage and it will work so i need to find a smarter way to check if the dxf has the minimum information

but for sure it needs an entrance and replacing classroom by meeting rooms can help

**Comment by agrignard** [comment]
@pacopaco74 and @cocsfav can you check it seems that the current version of the learning version on the git is the wrong one
https://github.com/CityScope/CS_Proxymix/commit/7027e8007dadd924ffaceed9d7e497197f9dbafe

maybe @pacopaco74 you need to repush it

**Comment by pacopaco74** [comment]
Yes it's definitely the wrong one

**Comment by pacopaco74** [comment]
I repushed a version with the good layers names 1d65ff9

**Comment by agrignard** [comment]
Ok it's better, however I think there is still an error in the unit of the file no? The building seems very very big 
<img width="1318" alt="Screenshot 2020-05-26 at 10 22 04" src="https://user-images.githubusercontent.com/3928502/82877819-f674f100-9f3a-11ea-8422-1bab0f5fc021.png">

**Comment by pacopaco74** [comment]
It seems correct to me... Do you still have this problem?

**Comment by agrignard** [comment]
it looks very long no? like 600 meter? Is that possible? I have the feeling that there is a factor of 10 here

**Comment by pacopaco74** [comment]
Strange.. I re-checked the DXF and its approximately 64 meters long, which seems coherent to me. When I run it on GAMA nothing crazy happens, it appears to me as big as the ENSAL model.
I don't know what's happening there... When you open the DXF on your computer it's 600 meters long ?

**Comment by pacopaco74** [comment]
The model in gama as it appears to me, compared to the ENSAL one :
<img width="1211" alt="Capture d’écran 2020-06-02 à 11 53 44" src="https://user-images.githubusercontent.com/60396205/83506752-dcea2100-a4c7-11ea-8787-b3daed5a3ef1.png">
<img width="1211" alt="Capture d’écran 2020-06-02 à 11 53 50" src="https://user-images.githubusercontent.com/60396205/83506761-e07da800-a4c7-11ea-9a7f-a34aa6abefba.png">

**Comment by ptaillandier** [comment]
I added (and committed) the unit for the Learning center: to do that, I
just created a csv file in the Learning_Center folder called building.csv
that defines the unit of the DXF file.
Is it ok now?

**Comment by agrignard** [comment]
It seems ok now I close this issue
