### ISSUE TITLE
ENSAL DXF Simplification

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#38]
In a first step, I think 2 things can be done for ENSAL

- Just choose one floor, Which one do you think is the more relevant? (we'll explore 3D and different floor in a next step)

- Also it seems that the file is pretty heavy, is there a way to simplify it a bit? Maybe with less object?

**Comment by pacopaco74** [comment]
We have done that this morning, @cocsfav is about to push it (he tried when everything collapsed ;-) We chose the RDC to begin with

**Comment by cocsfav** [comment]
I finish cleaning the plan, the DXF is very light but I have the impression that it does not work with the COVID model.
It looks like this :
![20200525_ENSAL_WorkInProgressDXF](https://user-images.githubusercontent.com/64479147/82829006-92a6e580-9eb2-11ea-8668-c00850896938.JPG)

**Comment by agrignard** [comment]
Which one is it ENSAL-1 or RDC?

Can you rename it to ENSAL and keep only one?

**Comment by cocsfav** [comment]
I'll rename it to ENSAL. How can I keep only a single file in the INCLUDES folder in the repo?

**Comment by agrignard** [comment]
What do you mean by a single file?

also do we need the .bak? If not you can remove them

**Comment by cocsfav** [comment]
I replaced ENSAL-RDC by ENSAL and I deleted ENSAL-1.
When I did the commit, an other commit appeared. I tried to revert it but I don't know if there still something wrong.
![20200525_ENSAL_PUSH](https://user-images.githubusercontent.com/64479147/82832852-a0616880-9ebc-11ea-92df-7613a585b121.JPG)

**Comment by agrignard** [comment]
I have the feeling that there is still something wrong no? It's still very long to instantiate the COVID model for ENSAL (like there are a lot of object in this file no?)

**Comment by cocsfav** [comment]
Normally there is not too many objects in the file, but is it possible that this is related to the many curves of the shape of the plan?

**Comment by pacopaco74** [comment]
Does GAMA support curved lines/forms in the DXF ? It seems to be going crazy when there are some

**Comment by ptaillandier** [comment]
For the moment, GAMA seems to not support it. I will try to see if it is
possible to improve that.

**Comment by ptaillandier** [comment]
So... taking into account the "curve" may be possible, but difficult (I
hate trigonometry: '(). I'll have to modify GAMA for that. Is it possible
to help me by providing a simple dxf file with only one or two elements
(curved walls)?

**Comment by cocsfav** [comment]
Hello @ptaillandier , In ly last commit I joined a DXF file with some curved walls.

**Comment by ptaillandier** [comment]
Good news, I have able to improve the DXF reader of GAMA. See the result obtained (with the latest version of GAMA)
![ensal](https://user-images.githubusercontent.com/1506077/83944689-bbf63880-a805-11ea-848f-57f9c508bfa4.PNG)
![test1](https://user-images.githubusercontent.com/1506077/83944690-bd276580-a805-11ea-9dc3-49eaaafa58b9.PNG)

**Comment by agrignard** [comment]
Yes! That's a great news!

**Comment by cocsfav** [comment]
Great news!

**Comment by agrignard** [comment]
OK this is what I have with the DXF Validator
<img width="1173" alt="Screenshot 2020-06-08 at 15 28 09" src="https://user-images.githubusercontent.com/3928502/84035867-af581880-a99c-11ea-9123-a580c40c60fd.png">

Is that coorect , it doesn't look exactly like yours?

**Comment by cocsfav** [comment]
That's right, it looks like the plan is displayed correctly.

**Comment by agrignard** [comment]
It seems that this issue is finally close. Thank you @ptaillandier and @cocsfav for your help!
