### ISSUE TITLE
San Sebastian Pedestrian File

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#41]
@ptaillandier the generate pedestrian file seems a bit simple

Any idea how to densify it?

<img width="1090" alt="Screenshot 2020-05-27 at 09 52 59" src="https://user-images.githubusercontent.com/3928502/82992874-0e627880-a000-11ea-89e0-5971efd1aef9.png">

**Comment by ptaillandier** [comment]
ah ah ... awful :p .
There are many parameters for the pedestrian path generator model. So it is possible, but a bit tricky (even me, I have some difficulties to determine the best parameter values for a dxf file). During the next days, I will try to generate better pedestrian paths for all the case studies and improve the pedestrian path generator model by adding commentaries.

**Comment by ptaillandier** [comment]
It is difficult to work with this DXF file because of the "hatching" that seems to represent walls on the left side.

**Comment by imartinezl** [comment]
Hi @ptaillandier,

What could I do about the DXF to improve the generated pedestrian path?
Is there a guideline for the "ideal" DXF file?

**Comment by ptaillandier** [comment]
Just having "plain" walls could be enough: on the attached picture you can
see an outside wall drawn with hatching in red, and the contour in green is
not closed. With GAMA it will be simpler to only have the complete contour
and not the hatching.

Le dim. 31 mai 2020 à 13:30, Iñigo Martínez <notifications@github.com> a
écrit :

**Comment by imartinezl** [comment]
Hi @ptaillandier,

I have removed the hatching from the walls, as you requested. The updated DXF is at the [SanSebastian branch](https://github.com/CityScope/CS_Proxymix/tree/sanSebastian). 

Also, from what I read on the issue #38, there may be some problems with the curve elements: Here is the difference between the generated shape on GAMA (1) vs opening the DXF file on Inkscape (2):

![Screenshot from 2020-06-02 13-12-43](https://user-images.githubusercontent.com/20516006/83514291-ad411600-a4d3-11ea-8bf4-29d2cb491b4e.png)
![Screenshot from 2020-06-02 13-20-34](https://user-images.githubusercontent.com/20516006/83514389-dd88b480-a4d3-11ea-8bf3-ee179774eca2.png)

**Comment by agrignard** [comment]
@imartinezl i think you can commit it on the master if you think the file is ok it will be easier than using branche for @ptaillandier

**Comment by imartinezl** [comment]
Yep, sorry for that. I just updated the DXF file on the master branch. I also tried to execute the [generate_pedestrian_network.gaml](https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/models/ToolKit/generate_pedestrian_network.gaml), but it appears to be an error at line 97:

![image](https://user-images.githubusercontent.com/20516006/83528404-5ba38600-a4e9-11ea-8b6a-2b509729abf1.png)

Error: `The primitive or action 'generate_pedestrian_network' cannot be resolved (either it is not defined or not accessible)`

(for your information I am running GAMA v1.8.0 on Ubuntu 18.04)

**Comment by agrignard** [comment]
Hi @imartinezl , we have made a change now in the model and it requires a pedestrian skills plugins to compile.

I have updated the readme to explain how to install the plugins.

Can you try to install it and see if it compiles for you?

**Comment by agrignard** [comment]
@imartinezl did you try to instal the plugin, I close this issue for now feel free to reopen it if needed
