### ISSUE TITLE
Layer name standardisation 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#43]
@pacopaco74 @cocsfav 

Structural
- Architectural Type: Type of Building (Offices, Public, Hospital)

- Space Type: Type of Spaces (rooms, meeting rooms, coffee, billetterie)

Behavior
- For each architectural type; Type of People (professor student)
- For teach type: a schedule

**Comment by pacopaco74** [comment]
**First attempt of definition of Building Types.** 
[Building Types.pdf](https://github.com/CityScope/CS_Proxymix/files/4716167/Building.Types.pdf)

To be discussed/rearranged together as it is quite hard to be both exhaustive and selective..
When done with that we could maybe go on with the definition of space types and try to assign them to every Building Type ? 

Would love to have your thoughts on that.

**Comment by agrignard** [comment]
Ok great first iteration. As we are also having this discussion in this other project so maybe it would make sense to follow the same standard
https://github.com/CityScope/cityscope.github.io/issues/15
where we basically use this standard in us 
https://planning-org-uploaded-media.s3.amazonaws.com/document/LBCS.pdf

Do you think you can explore maybe a version with the corresponding LBCS code?

**Comment by cocsfav** [comment]
Ok great we will explore a version corresponding LBCS code.

**Comment by pacopaco74** [comment]
Ok great. So I guess the next move would be to define standard space types (rooms, meeting rooms, coffee, toilets,...) for every one of the 20 Architectural types ? and try to keep the number of space types as low as possible ?

**Comment by agrignard** [comment]
https://openlab.citytech.cuny.edu/arch-1230/files/2014/08/AIA-Layer-Standards.pdf

**Comment by agrignard** [comment]
See #78

**Comment by agrignard** [comment]
Reopening it as by discussing with @MarkusElKatsha we quicklu figure out that #78 was made for architectural artefact not for spaces so I reopen this issue for now

**Comment by pacopaco74** [comment]
Hey @agrignard ! With @cocsfav we did review the different type of classification (IBC, LBCS, etc) and tried to choose the best one. However it seems to us that, as complete as they are, they might be not very suitable to our goal which is create an adaptative layer system for each building we will put inside the simulation. Indeed, those classifications were often designed with an other purpose in mind and we feel like it would be overwhelming and confusing for a potential user. You will find below an other iteration that we propose and which mixes together various classification systems. We would love to discuss about it before starting developing every categories into sub-categories (as in red on the image below) which will be a lot of work to accomplish
<img width="464" alt="Capture d’écran 2020-07-06 à 15 41 21" src="https://user-images.githubusercontent.com/60396205/86600454-6053d200-bfa0-11ea-8136-6d73ab1cc302.png">

**Comment by agrignard** [comment]
Thank you @pacopaco74 and @cocsfav for your precious input on this. I close this issue for now as the project is currently really focus on Covid in Guadalajara. But all this inout are anyway stored and will be reuse later
