### ISSUE TITLE
Impossible to run model

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#45]
I don't knwo wht have change , I guess it's a very small change but I cannto figure it out

Try to run for instance DailyRoutine.gaml

get the follwoing error

`````
2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in file<point, unknown> the_dxf_metadata <- file_exists((dataset_path + useCase) + '/building.csv') ? (csv_file((dataset_path + useCase) + '/building.csv',',',true)) : nil ;
NullPointerException: null
msi.gama.common.util.FileUtils.findInWorkspace(FileUtils.java:157)
msi.gama.common.util.FileUtils.constructAbsoluteFilePath(FileUtils.java:134)
msi.gaml.operators.Files.exist_file(Files.java:115)
gaml.additions.GamlAdditions.lambda$550(GamlAdditions.java:611)
msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:84)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:75)
when applying the file_exists operator on ./../../includes/Factory/building.csv
in initializing attribute the_dxf_metadata
in agents Simulation 0, COVID0
`````

**Comment by agrignard** [comment]
I don't know if it can help but Gama is now me this when I open it
<img width="635" alt="Screenshot 2020-06-09 at 22 45 37" src="https://user-images.githubusercontent.com/3928502/84197931-0f38e700-aaa3-11ea-961c-2032605385ce.png">

**Comment by ptaillandier** [comment]
I don't think so. It is more linked to the management relative path in models that import other models and to the fact that GAMA does not like relative paths that concern a file outside the project location.

My fix should be ok for the Proxy project, and I reported an issue about this on the GAMA github: https://github.com/gama-platform/gama/issues/2997.
