### ISSUE TITLE
Density Management

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#47]
One of the main action that is taken for a post covid world is to reduce the density of a building.

The way I see it could be for a given building knowing the activity of people

1. We run a "normal" scenario with 100% of the people to have the ground truth and to get the Maximum scenario (the max number of peopel is a common paramter for any building (at least in US, btw it would be ,ice to include it in the dxf file, or in building.csv)
2. Give the possibility to the user to just play with the density (e.g only 50% of the people are allowed)
     2.1 In the first case people go to the initial layout for there desk (some people might be closer to another)
     2.2 Gama Provides an optimal spacing ```` places `````that would be computed initially depending on the density 

Question asked by @ptaillandier 
density (limiting people entering a space) : What happens when someone wants to enter a room that's already "too crowded"? Will people line up to enter the room? Go somewhere else? 
=> At the buildign level people will just not enter, at the room level maybe we can assign it to another room but I woudl imagine that scenario 1 is the maximum we can have , so you will never have to much people in a room if I am not wrong

**Comment by agrignard** [comment]
Right now the number of people is compted according to the number of available spaces

see this part of the code 

``````
reflex people_arriving when: not empty(available_offices) 
	{	
		  do create_people(rnd(0,min(5, length(available_offices))));
	}
``````

Then the density should impact on the number of workstations see #48

**Comment by ptaillandier** [comment]
I've defined four scenarios:
- "data": use actual data on the location of the workstations. For now, do nothing, but once the data is integrated in the dxf, it should be easy to define this scenario. 
- "distance": minimum distance between workstations (using the "distance_people" parameter) 
- "num_people_building": Total number of people in the building (i.e. number of work centers in the building). The model tries to define a "smart" location for each workstation in offices (not so smart, but ok for a v0).
- "num_people_room": number of people per office (i.e. number of workstations in each office/room). It should be easy to integrate (one line to add to the code) once the data is integrated in the dxf (or in the csv).

**Comment by agrignard** [comment]
@ptaillandier I guess it's a bit similar thatn distance, but it coudl be usefull to provide also a "density" scneario (density per building but also per offices)

**Comment by agrignard** [comment]
fixed with the 4 scenarios proposed by @ptaillandier
