### ISSUE TITLE
Missing elements in MediaLab 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#64]
@nayoub or @pacopaco74 or @cocsfav do you think you can have a look at the Medialab dxf file and add the follwoing elements at least Entrance and elevators ? 

@nayoub as you know better the palce it might be easier if you can do it.

<img width="519" alt="Screenshot 2020-06-10 at 12 24 03" src="https://user-images.githubusercontent.com/3928502/84257230-51027580-ab15-11ea-8df3-312591ae0714.png">

**Comment by agrignard** [comment]
entrance (previsously primary elevators) and elevators ( previously secondary elevators) have been added

However the offices are not alll well located (no cityscience for instance)
<img width="1774" alt="Screenshot 2020-06-10 at 12 32 16" src="https://user-images.githubusercontent.com/3928502/84258022-8eb3ce00-ab16-11ea-8285-21f83c800558.png">

**Comment by agrignard** [comment]
Ok so we with @nayoub have identify the problem but for an AutoCAd reason we cannot fix it.

So in the MediaLab dxf file there is lot of layer that has the name E15-XXX (e. E15-389, E15-368 etc), those layer shoudl be names 'offices' instead. I am trying to make this modificaation with AutoCad but when I reload the newly created dxf file I have an error.

@pacopaco74 and @cocsfav woudl you mind having a look? the goal would be 

1. To change the layer name of all the EXX_YYY to Offices and then run the DailyRoutine model

**Comment by agrignard** [comment]
The file is in includes/MediaLab/building.dxf

**Comment by cocsfav** [comment]
Okay I'll take a look!

**Comment by agrignard** [comment]
@cocsfav if you commit a new file commit it with a new name. I tried to merge it in autocad but i don't knwo why it doesnt work

**Comment by cocsfav** [comment]
Ok!

**Comment by agrignard** [comment]
This is the one that works (with E_15-XXX)
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/MediaLab/building.dxf
and the oen merged that doesnt work
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/MediaLab/building-test.dxf

**Comment by agrignard** [comment]
OK hold on for this issue, the dxf is ok it seems to come from the pedestrian_path that should be recomputed

**Comment by ptaillandier** [comment]
It is working now (I changed the name of the old file building_old.dxf and building-test.dxf is now building.dxf)

**Comment by agrignard** [comment]
Great thank you Patrick!!! looks now very cool and realistic!
<img width="1126" alt="Screenshot 2020-06-11 at 18 52 31" src="https://user-images.githubusercontent.com/3928502/84416603-b9844c00-ac14-11ea-9b61-eae8715fca35.png">
