### ISSUE TITLE
Accelerate time when everyone is ariving

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#66]
Right now in the medialab people arrive at 7 and in 5min there are all in there offices, then it takes too long to speed up the simualtion to go to lunch.

**Comment by agrignard** [comment]
It seems that the step stays stuck at 1 evn when hour >7 and minute >10

````
h7m 11 current step1.0
and 
lenght people empty 2
````

So it means that someone didn't reach is target, so the ste never go to 5#min
How can we be sure that everyoen reach his target?

**Comment by agrignard** [comment]
This 2 guys 
<img width="405" alt="Screenshot 2020-06-11 at 10 07 55" src="https://user-images.githubusercontent.com/3928502/84361121-7651bb00-abcb-11ea-87b4-10d19ee0e4d6.png">

**Comment by ptaillandier** [comment]
I am working on it

Le jeu. 11 juin 2020 à 10:05, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by ptaillandier** [comment]
done
