### ISSUE TITLE
Add the real desk in the media Lab

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#67]
@nayoub even if it's a bit rough we will need (in order to compare the before covid world with the after) to have the placement of the real workstation

**Comment by agrignard** [comment]
Right now the space/desk (green point ) are generating according to the maximum distance between desk (2.0 meter in this case) but it would be great to have the current layout even if it's rough 
<img width="1200" alt="Screenshot 2020-06-16 at 22 40 20" src="https://user-images.githubusercontent.com/3928502/84825895-6fd79f00-b022-11ea-8963-c934ec1a5eb1.png">

**Comment by agrignard** [comment]
THis is the 3rd floor buildign where a layer desk could be added
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/MediaLab/building.dxf

**Comment by LAAP** [comment]
OK @agrignard , I will try to do it

**Comment by agrignard** [comment]
@LAAP here is the dxf file of CityScience
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/CityScience/building.dxf

As it is it is consider as buildign like any other (it means the ABM is working like in the mediaLab) so do not change this , but the idea would be to copy past this "object" to then integrate it in this one labbelled as desk
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/MediaLab/building.dxf

**Comment by LAAP** [comment]
@agrignard ,
Awesome! I will try to do this tonight

**Comment by LAAP** [comment]
@agrignard ,

I have "refreshed the Github desktop", and all the files are the ones without furniture.  When I opened the file I don't find the "CS Lab" with the fourniture. I only see a flipped 3rd floor plan:

<img width="1230" alt="Captura de pantalla 2020-06-17 a las 21 40 59" src="https://user-images.githubusercontent.com/19315213/84968095-b3dea880-b0e3-11ea-93c6-9c97fea29786.png">


Please, can you share the one the @nayoub made with the furniture of our CS Lab? Also, if you could send it by email as a backup plan, just in case, so we do not lose tomorrow in GitHub conversation just for getting a file.

Thank you very much! And sorry for being new in Github-file transferring

**Comment by agrignard** [comment]
So this one is the 3rd floor of the lab without fourniture
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/MediaLab/building.dxf

and this one is just the CityScience (but using the same standardisation layer as the MediaLab so we can run the ABM)
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/CityScience/building.dxf

So the idea is to copy paste the layer "offices" in the CS and paste it as a layer desk in the media lab

**Comment by LAAP** [comment]
Awesome! Thank you @agrignard ,

Yes, I think I was looking in the wrong folder  ;)

**Comment by LAAP** [comment]
Hi @agrignard ,

I have finished the dxf furniture floor plan:

<img width="927" alt="Captura de pantalla 2020-06-18 a las 19 46 21" src="https://user-images.githubusercontent.com/19315213/85082308-80138980-b19c-11ea-9bed-11200e7df33e.png">

The file is: ML_3_L.dxf

I will push it

**Comment by nayoub** [comment]
Super cool @LAAP

________________________________

**Comment by agrignard** [comment]
Nice @LAAP can you push it?

**Comment by agrignard** [comment]
@LAAP I don't think you commited the right file this is what i have in ML_3.dxf no desk)
<img width="1223" alt="Screenshot 2020-06-19 at 15 33 44" src="https://user-images.githubusercontent.com/3928502/85138013-56ad3900-b242-11ea-9a89-730592a4df6d.png">

**Comment by agrignard** [comment]
I think the one you cmiit is ML_3_L.dwg but i cannot format it to .dxf can you do it?

**Comment by agrignard** [comment]
also I see that there are some chair, are they in a different layer or attached to a specific desk?

**Comment by LAAP** [comment]
@agrignard , OK, I will try to do this

**Comment by LAAP** [comment]
@agrignard ,

Done. I have updated the floor plan with tables and chairs and shave it as a dxf, and pushed.

I am closing this issue
