### ISSUE TITLE
Cannot run daily routine

### ISSUE THREAD

**Issue by tnguyenh** [CityScope/CS_Proxymix#69]
3 occurrences in 3 agents at cycle 0: Java error: nil value detected
in float dist <- max([1.0,distance_to(self,closest_to(wall,self))]);
NullPointerException: null
msi.gama.metamodel.shape.GamaShape.euclidianDistanceTo(GamaShape.java:595)
msi.gama.metamodel.agent.AbstractAgent.euclidianDistanceTo(AbstractAgent.java:130)
msi.gama.metamodel.topology.continuous.ContinuousTopology.distanceBetween(ContinuousTopology.java:115)
msi.gaml.operators.Spatial$Relations.distance_to(Spatial.java:3737)
gaml.additions.GamlAdditions.lambda$909(GamlAdditions.java:972)
msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
when applying the distance_to operator on pedestrian_path(0) and nil
in float dist <- max([1.0,distance_to(self,closest_to(wall,self))]);
in ask pedestrian_path  {
	float dist <- max([1.0,distance_to(self,closest_to(wall,self))]);
	do initialize (obstacles:[wall], distance:dist);
	free_space <- free_space.geometries first_with overlaps(each,shape);
}

in ask pedestrian_path  {
	float dist <- max([1.0,distance_to(self,closest_to(wall,self))]);
	do initialize (obstacles:[wall], distance:dist);
	free_space <- free_space.geometries first_with overlaps(each,shape);
}

in action initialize_pedestrian_model  {
	ask pedestrian_path  {
		float dist <- max([1.0,distance_to(self,closest_to(wall,self))]);
		do initialize (obstacles:[wall], distance:dist);
		free_space <- free_space.geometries first_with overlaps(each,shape);
	}

}

in do initialize_pedestrian_model ;
in if movement_model = pedestrian_skill  {
	do initialize_pedestrian_model ;
}

in init  {
	validator <- false;
	do initiliaze_dxf ;
	create pedestrian_path from: pedestrian_path_shape_file ;
	pedestrian_network <- as_edge_graph(pedestrian_path);
	loop se over: the_dxf_file  {
		string type <- get(se,layer);
		if type = walls  {
			create wall with: [shape::clean(polygon(se.points))];
		}else  {
			if type = entrance  {
				create building_entrance with: [shape::polygon(se.points), type::type];
			}else  {
				if type in ([offices,supermarket,meeting_rooms,coffee,storage])  {
					create room with: [shape::polygon(se.points), type::type];
				}
			
			}
			
		
		}
		
	
	}

	if density_scenario = 'num_people_building'  {
		list<room> offices_list <- room where (each.type = offices);
		float tot_area <- sum_of(offices_list,each.shape.area);
		ask offices_list  {
			num_places <- max([1,round((num_people_building * shape.area) / tot_area)]);
		}
	
		int nb <- sum_of(offices_list,each.num_places);
		if (nb > num_people_building) and (length(offices_list) > num_people_building)  {
			loop times: nb - num_people_building  {
				room r <- one_of(offices_list where (each.num_places > 1));
				r.num_places <- r.num_places - 1;
			}
		
		}else  {
			if nb < num_people_building  {
				loop times: num_people_building - nb  {
					room r <- one_of(offices_list);
					r.num_places <- r.num_places + 1;
				}
			
			}
		
		}
		
	
	}

	ask room + building_entrance  {
		do intialization ;
	}

	ask wall  {
		if not(empty((room + building_entrance) inside self))  {
			shape <- shape.contour;
		}
	
	}

	ask room  {
		list<wall> ws <- wall overlapping self;
		loop w over: ws  {
			if covers(w,self)  {
				do die ;
			}
		
		}
	
	}

	ask room + building_entrance  {
		geometry contour <- nil;
		float dist <- 0.3;
		loop while: contour = nil  {
			contour <- copy(shape.contour);
			ask wall at_distance 1.0  {
				contour <- contour - (shape + dist);
			}
		
			ask (room + building_entrance) at_distance 1.0  {
				contour <- contour - (shape + dist);
			}
		
			dist <- dist * 0.5;
		}
	
		if contour != nil  {
			entrances <- points_on(contour,2.0);
		}
	
		ask places  {
			point pte <- closest_to(myself.entrances,self);
			dists <- distance_to(self,pte);
		}
	
	}

	map<string, list<room>> rooms_type <- room group_by each.type;
	loop ty over: rooms_type.keys - ([offices,entrance])  {
		create activity  {
			name <- ty;
			activity_places <- rooms_type[ty];
		}
	
	}

	create working ;
	create going_home_act with: [activity_places::list<building_entrance>(building_entrance)];
	create eating_outside_act with: [activity_places::list<building_entrance>(building_entrance)];
	available_offices <- rooms_type[offices] where (each.is_available());
	if movement_model = pedestrian_skill  {
		do initialize_pedestrian_model ;
	}

	ask building_entrance  {
		if not(empty(pedestrian_path))  {
			list<pedestrian_path> paths <- pedestrian_path at_distance 10.0;
			if movement_model = 'moving skill'  {
				closest_path <- paths with_min_of distance_to(each,location);
			}else  {
				closest_path <- paths with_min_of distance_to(each.free_space,location);
			}
			
		
			if closest_path != nil  {
				init_place <- inter(shape,closest_path);
				if init_place = nil  {
					init_place <- closest_points_with(shape,closest_path)[0];
				}
			
			}else  {
				init_place <- shape;
			}
			
		
		}else  {
			init_place <- shape;
		}
		
	
	}

}

in agents pedestrian_path0, Simulation 0, DailyRoutine0

**Comment by ptaillandier** [comment]
Hi Tri,
Do you have the  error everytime and just sometimes?
Which version of GAMA are you using? Could you try with the latest
continuous build:
https://github.com/gama-platform/gama/releases/tag/continuous ?

Le ven. 12 juin 2020 à 12:13, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Yes everytime with the daily

**Comment by tnguyenh** [comment]
Hi Patrick,

yes I tried with the latest continuous build. Actually it works well with the regular release, but not the daily build. And of course I can't use the regular release since it does not work with COMOKIT...

**Comment by ptaillandier** [comment]
strange... On my computer (windows as well), the latest continuous build
works well. Could you try to create a new workspace?

Le ven. 12 juin 2020 à 15:24, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by tnguyenh** [comment]
Yes, I tried to create a new workspace, reinstall Gama... no way. So strange, but I've always had some kind of Karma problem with Gama...

**Comment by agrignard** [comment]
Ok so one good news and one bad news: 

- The good news is that @tnguyenh you are not the only one to have this issue

- The bad news is that @LAAP is also having this issue... see #70

**Comment by agrignard** [comment]
This model is working for @ptaillandier and @agrignard .  @cocsfav , @pacopaco74 and @nayoub can you run this model to see if it works for you?

**Comment by LAAP** [comment]
@agrignard Thank you... I do not feel lonely in the world anymore  ;)

**Comment by agrignard** [comment]
@LAAP and @tnguyenh we might be lucky (or not) the very last version of GAMA 1.8.1 has just been released (however it should be very similar to the one you just download) but it could help if we all run the same version.

So when you have time can you download it ?
here
https://github.com/gama-platform/gama/releases/tag/1.8.1

**Comment by LAAP** [comment]
Bad news @agrignard ... GAMA 1.8.1:

<img width="1431" alt="Captura de pantalla 2020-06-16 a las 16 37 17" src="https://user-images.githubusercontent.com/19315213/84825651-beb81100-afef-11ea-8ac6-c7492591094a.png">

**Comment by agrignard** [comment]
Ok I was expecting that as the release is from today and you donwload it your like yesterday or today, we'll keep investgating with @ptaillandier

**Comment by ptaillandier** [comment]
Today, I made this test:
1. I downloaded the continuous build of GAMA (here: https://github.com/gama-platform/gama/releases/tag/continuous) -> GAMA1.8_Continuous_withJDK_Win_06.17.20_1a29564.zip

2. I ran GAMA and created a new workspace

2. I installed the "pedestrian" plugin (if the installation goes well, GAMA should ask you if you are sure that you want to install the plugin, and propose to restart GAMA).

3. I downloaded the model (directly the archive from the github: https://github.com/CityScope/CS_Proxymix/archive/master.zip

4. in GAMA, I imported the downloaded file

and it works well.

**Comment by agrignard** [comment]
Thanks @ptaillandier for testing this again, this is very unforunate you are on windows an it works I am on mac and it work @tnguyenh is on windows and it doesnt' work and @LAAP is on mac and it doesn't work...

I dont know how we can fix that

Can we blindly test if all of this guys are nil we give another value for dist?

``````
float dist <- max([1.0,distance_to(self,closest_to(wall,self))]);
`````` 

@tnguyenh can you print ````wall````here to see if it's null, then if it's null we do something ? but what ;-)?

**Comment by agrignard** [comment]
Also I don't know if it's because of this but some hiden file has been push by mistake in the github, can it affect the behavior of other conf?

<img width="1011" alt="Screenshot 2020-06-17 at 23 09 53" src="https://user-images.githubusercontent.com/3928502/84950806-bd6e0d80-b0ef-11ea-9ad1-81b2a0138723.png">

I will remove them and @LAAP and @tnguyenh you can retry if you have time (not sure at all if it will change something)

**Comment by tnguyenh** [comment]
@ptaillandier : I followed this procedure several times, the last time using the links you provided in this issue. Sadly I still have the same problem.

@agrignard : nice try, but that would have been too easy....

**Comment by tnguyenh** [comment]
@ptaillandier : if you want to blindly debug this, if it can help, I tried the following code, if it can be of any help:

````ask pedestrian_path {
			write pedestrian_path_shape_file;
			write length(wall);
			write self;
			write wall closest_to self;
			float dist <- max(1.0, self distance_to (wall closest_to self));
  }````

I got the following output:

C:/Users/Tri/Documents/GitHub/CS_Proxymix/ProxymixABM/includes/MediaLab/pedestrian_path.shp
557
pedestrian_path(0)
nil

**Comment by agrignard** [comment]
OK I like the concept of the blind debugging ;-) So now at least we know the wall is nil in your case (and I guess in @LAAP case)

**Comment by pacopaco74** [comment]
@agrignard daily routine doesn't seem to work for me neither :
<img width="1755" alt="Capture d’écran 2020-06-18 à 09 50 04" src="https://user-images.githubusercontent.com/60396205/84993375-8593b400-b149-11ea-8330-9e6486c521e1.png">

I am on Mac OS / Gama 1.8.0

**Comment by cocsfav** [comment]
@agrignard I have the same problem on Windows with Gama v.1.8.0 ;
![20200618_error-DailyRoutine](https://user-images.githubusercontent.com/64479147/84996965-4320a600-b14e-11ea-89ed-e93312c626ea.JPG)

**Comment by agrignard** [comment]
This is a different error, in your case you cannot even run the model as it's red.

Did you successfully install the plugin?  following this methodology? 
https://github.com/CityScope/CS_Proxymix/issues/69#issuecomment-645500336

**Comment by tnguyenh** [comment]
> 
> 
> OK I like the concept of the blind debugging ;-) So now at least we know the wall is nil in your case (and I guess in @LAAP case)

Nope, we can only know that 'wall closest_to self' is nil. There are 557 walls, self is pedestrian_path(0).

**Comment by ptaillandier** [comment]
hum...
 Could you try:

write (wall with_min_of (each distance_to self));
To see if the problem comes from the quadtree or not.


Le jeu. 18 juin 2020 à 11:20, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by tnguyenh** [comment]
Just tried this:

````
ask pedestrian_path {
			write length(wall);
  			write self;
			ask wall{
				write self distance_to myself;
			}
			write wall closest_to self;
}
````

The ouput is:
557
pedestrian_path(0)
2.8718905361467674E7
2.8718905247671742E7
2.8718865907673366E7
2.871886590762366E7
...
2.87189146773129E7
nil

It looks like that there is no problem in computing the distance (and also that this distance exists for every walls). Is it a problem with closest_to applied to a pedestrian_path agent ?

**Comment by tnguyenh** [comment]
> hum... Could you try: write (wall with_min_of (each distance_to self)); To see if the problem comes from the quadtree or not. 

Yep. The code:

````
	ask pedestrian_path {
			write length(wall);
			write self;
			write (wall with_min_of (each distance_to self));
			write wall closest_to self;
}
````
And the corresponding output:

557
pedestrian_path(0)
wall(163)
nil

**Comment by ptaillandier** [comment]
The distance is totally wrong :p ...
Could you write:

write "self loc: " + location + "wall location:" + (wall with_min_of (each
distance_to self)).location + " world location:" + world.location;

Le jeu. 18 juin 2020 à 11:26, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by tnguyenh** [comment]
Yep, here is the output:

self loc: {-2.871886773199296E7,-382.30760529874203,0.0}wall location:{0.1381745117187525,9.19277014973955,0.0} world location:{47.44719793294267,29.541215958658835,0.0}

**Comment by ptaillandier** [comment]
So, I thinK I found the problem.
In the experiment folder, could you add:
action _init_ {
gama.pref_gis_auto_crs <- false;
gama.pref_gis_default_crs <- 3857;
create simulation;
}

Le jeu. 18 juin 2020 à 11:50, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by ptaillandier** [comment]
I mean, in the experiment block

**Comment by tnguyenh** [comment]
With the other shapefiles, same problem with odd location. For Factory:

self loc: {-2.871861860684365E7,30.4324622049827,0.0}wall location:{0.4500000219349749,18.622013018384592,0.0} world location:{52.9521003597391,17.962324640434385,0.0}

**Comment by tnguyenh** [comment]
OK, got this error:

![image](https://user-images.githubusercontent.com/18676913/85007393-c399d380-b15b-11ea-898d-3632bcbd5dd7.png)

**Comment by ptaillandier** [comment]
Ok,

Try to remove "action _init_" .
In preference (Help menu -> preferences), in the "data and operators"
panel, check that you have the same value as me in GIS Coordinates
References Systems:

[image: image.png]
And run again the model

Le jeu. 18 juin 2020 à 12:04, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
THis is what I have 
<img width="1269" alt="Screenshot 2020-06-18 at 12 39 09" src="https://user-images.githubusercontent.com/3928502/85010710-bdf2bc80-b160-11ea-98e1-81273af4c370.png">

**Comment by LAAP** [comment]
Wow! Thank you to all of you for this effort  ;)

**Comment by agrignard** [comment]
@LAAP can you check your preferences?  You go to Help -> Preferences -> Data and Operators and make a screenshot

**Comment by LAAP** [comment]
Sure! @agrignard , here it is:

<img width="1438" alt="Captura de pantalla 2020-06-18 a las 9 18 39" src="https://user-images.githubusercontent.com/19315213/85024957-c3420e00-b144-11ea-9edb-0589e70eb6dc.png">

**Comment by agrignard** [comment]
Ok so at least we do'nt have the same value in the EPSG but we both have the let GAMA to true.

@ptaillandier any idea?

**Comment by ptaillandier** [comment]
Yes
 Just change " or use the following epsg...." to 3857

Le jeu. 18 juin 2020 à 16:08, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Ok but what I don't get is that there are some .prj right so GAMA will find it no?

In any case @LAAP can you try this 

replace 32648 per 3857 to see if it works

**Comment by tnguyenh** [comment]
@ptaillandier : I can't see the image you posted, but I assume you have the same value than Arnaud.

I've got the same than Luis:

![image](https://user-images.githubusercontent.com/18676913/85041854-c364fc80-b18a-11ea-860d-7f6485dd7390.png)

**Comment by tnguyenh** [comment]
> 
> 
> Ok I get it. so the dxf doesn't have a prj that's why Gama will use the definied one
> 
> In any case @LAAP can you try this
> 
> replace 32648 per 3857 to see if it works

That works !

![image](https://user-images.githubusercontent.com/18676913/85041974-e8f20600-b18a-11ea-9172-5e0e62003a70.png)

**Comment by tnguyenh** [comment]
Why do we have different values in the preferences ?

**Comment by ptaillandier** [comment]
You have the default value, but not Arnaud and me (a long story....).
I will try to find a smart way to fix this error for "new" users.

Le jeu. 18 juin 2020 à 17:42, Tri Nguyen-Huu <notifications@github.com> a
écrit :
