### ISSUE TITLE
I can't run the Gama model

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Proxymix#70]
Hi @agrignard ,

Since we activate the plugging few days ago, I can't run the Gama model:

<img width="433" alt="Captura de pantalla 2020-06-12 a las 13 49 32" src="https://user-images.githubusercontent.com/19315213/84532510-5a761400-acb4-11ea-9a8d-815dac758b6f.png">

**Comment by agrignard** [comment]
It can be interesting to see what's is written in the .log file, anyway did you try to create a new workspace? It should resolve the problem

**Comment by LAAP** [comment]
Hi @agrignard ,

Yes, I have, and same issue: 

<img width="456" alt="Captura de pantalla 2020-06-15 a las 10 08 31" src="https://user-images.githubusercontent.com/19315213/84667395-49194b80-aef0-11ea-9b5a-eb50b820172d.png">

And this is what the folder has... nothing!:

<img width="1281" alt="Captura de pantalla 2020-06-15 a las 10 08 43" src="https://user-images.githubusercontent.com/19315213/84667422-56363a80-aef0-11ea-8bdc-71fb841f49f4.png">

Since we put the "plugin" is not working anymore...

**Comment by agrignard** [comment]
OK I see. The plugin has been installed on the current 1.8 it should be installed on a newer version of GAMA

Woudl it be possible for you to use it on the lasted GAMA release that you can find here
https://github.com/gama-platform/gama/releases/tag/continuous

Most of your already working GAMA project should be compatible

**Comment by LAAP** [comment]
@agrignard ,
OK, awesome! Done, now, which one is the simulation that I should run?:
<img width="358" alt="Captura de pantalla 2020-06-16 a las 10 25 53" src="https://user-images.githubusercontent.com/19315213/84787346-dfff0a00-afbb-11ea-8ea2-53a82f9e67ca.png">

**Comment by agrignard** [comment]
DailyRoutine for just the peopel moving
CityScope Coronaizer_XX for the epidemiologic model plugged on top of it

**Comment by LAAP** [comment]
@agrignard ,
They are both in read. hahahahha!

**Comment by agrignard** [comment]
Did you install the plugin on the new version of GAMA??

**Comment by LAAP** [comment]
@agrignard ,
Nop. i don't remember how to do it. Do you have a tutorial?

**Comment by agrignard** [comment]
Everything is written on the Readme

**Comment by LAAP** [comment]
@agrignard ,

I have installed the plugin, and now is giving some issues:

<img width="1438" alt="Captura de pantalla 2020-06-16 a las 13 41 41" src="https://user-images.githubusercontent.com/19315213/84808824-3f1e4800-afd7-11ea-8b5a-3c073c0807c2.png">

**Comment by agrignard** [comment]
can you expand the error (right click on it and do copy to clip board). maybe it's the same issue as what @tnguyenh has here https://github.com/CityScope/CS_Proxymix/issues/69

**Comment by LAAP** [comment]
Sure!
<img width="557" alt="Captura de pantalla 2020-06-16 a las 14 03 04" src="https://user-images.githubusercontent.com/19315213/84810985-25323480-afda-11ea-9689-b921b7643f81.png">

**Comment by agrignard** [comment]
Ok so one good news and one bad news: 

- The good news is that wr can close this issue as @tnguyenh as the same one #69

- The bad news is that we do'nt knwo how to solve it... @tnguyenh is on Windows , what abotu you @LAAP which version of Mac are you using?

This model is working for @ptaillandier and I, @cocsfav , @pacopaco74 and @nayoub can you run this model to see if it works for you?

**Comment by agrignard** [comment]
Just reopening it to be sure that it's also working for @LAAP
