### ISSUE TITLE
Add a Dynamic Instantaneous Porximity heatmap

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#71]
Shouldn't be that hard to have this kind of features
https://www.arup.com/news-and-events/return-to-the-workplace-with-arup-space-explorer

**Comment by agrignard** [comment]
@ptaillandier any idea on how to do that?

**Comment by agrignard** [comment]
For inspiration 
https://www.burohappold.com/articles/social-distancing-in-the-workplace/

**Comment by ptaillandier** [comment]
A simple first solution was implemented.
The visual aspect can be improved (for example, color), but, at least, it works.
The size of the grid used for the computation can be defined through a global variable (by default, 0.5 meters, to avoid to heavy computation) and the masked_by operator can be used (optional : false by default) to improve the realism of the result.

**Comment by agrignard** [comment]
Great! it seems to work pretty well, I wil explore a bit the parameters 

<img width="1164" alt="Screenshot 2020-06-30 at 11 37 58" src="https://user-images.githubusercontent.com/3928502/86110698-2b3e1000-bac6-11ea-93d8-8e53309b528b.png">

**Comment by agrignard** [comment]
Maybe a little thing to change for me it seems that if 2 pepel are well cited on their site then the proxymity map shoudl exist (they are in a "safe" place) isn't it?

<img width="94" alt="Screenshot 2020-06-30 at 11 59 46" src="https://user-images.githubusercontent.com/3928502/86113332-6aba2b80-bac9-11ea-9360-3b19aaace116.png">


How ever I see some blue close to peopel that re sitted? I guess is just cahnging maybe by a factor 2 the way the grd is computed ?

**Comment by agrignard** [comment]
I reduce people at_distance distance_people -0.1#m

but still

<img width="647" alt="Screenshot 2020-06-30 at 15 02 20" src="https://user-images.githubusercontent.com/3928502/86129336-ce048780-bae2-11ea-8279-8c831adbfa39.png">

**Comment by agrignard** [comment]
Ok this is fixed. One last thing before to close this issue would be the availability to show instantaneous but alos aggregated grid to keep a trace of where there has been a potential danger
