### ISSUE TITLE
New Wish List 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#72]
How the behavior patterns of users of university centers should be modified for the gradual return to face-to-face courses considering the following optimal conditions:
Density
Paths
Social distancing
Safety/hygiene measures
Use of common/public areas
Transport access
Mobility as a result of emergent behaviors (avoiding space-time matches)

**Comment by LAAP** [comment]
@agrignard ,

This is not the official list yet, but it is a good starting point

**Comment by agrignard** [comment]
I close this isse are this is redundant with what has alreayd been discussed
