### ISSUE TITLE
Time Shifting

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#73]
Right now everyone arrives at the same time and have a very classic day, we will need to explore time shifting scenarios or even 24hours day, etc

**Comment by agrignard** [comment]
How do we proceed on that, @LAAP maybe by inspiration with the whatever dining room curve, we could end up with a specific time where people can stay. However how can we specify this time? Would it be in link with the ventilation of the space?

**Comment by LAAP** [comment]
Hi @agrignard ,

Yes, as soon as we have the density, we could have sift of people, and in between, maybe 1 agent gets in to the room and "cleans" or similar. 

Do we have different profiles? Students, Teachers, staff?

**Comment by agrignard** [comment]
Not specific enough

**Comment by LAAP** [comment]
Hi @agrignard ,

I am reopening this issue. I think time in the room is important. I think that, if we can't calculate the time from the simulation, at least we should follow the IDSS graph below.

Seems to me that, **if we follow the 0.003 curve** (and if we integrated in the simulation), we will be in the side of safety: in this curve, **30 people** in a room with masks and keeping social distancing can not stay longer than **45-60 min**:


<img width="991" alt="Captura de pantalla 2020-08-26 a las 10 58 30" src="https://user-images.githubusercontent.com/19315213/91320268-53c34d00-e78b-11ea-8124-909faa5affc9.png">
Please, let me know your thoughts

Luis

**Comment by agrignard** [comment]
See #117
