### ISSUE TITLE
Desk management: from file or generated

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#75]
@ptaillandier would you mind having a look in the code to have this features:

Having a boolean that gives the possibility to instanciate the desk (what you call spaces) form the dxf or programmtically . The idea would be the following

if you have desk object in your dxf then you can instanciate it so run the simulation on the current layout of the building, if you don't have it (or if we want to propose a new layout) then the desk would be instanciated programmatically. Then we can also think abotu different layout generator in a second step (see https://github.com/CityScope/CS_Proxymix/issues/48)

@LAAP has been producing a dxf for the media lab with the desk layer, unfortunately he didn't push it, yet, I'll let you know as soon as it's pushed. 

Maybe you want to blindly create the structure of the code until the dxf is pushed?

**Comment by agrignard** [comment]
thank you @LAAP 

@ptaillandier if you want to have a look the new file is mediaLab/building and tehy are chair and desk layer

**Comment by agrignard** [comment]
This dxf and working with architech is definetely chalenging...

So I cannot open the dxf in my autocad because it's autocad2018... (wa 2 years and it's already not comaptible)

Aslo Luis you didn't startt from the vurrent building files, so in your ML_3_L_Whatever.dwg there is no entrance (I think you strated from ML_3/dxf...

ah architect....

I will try to fix this by self with my very ooooooooooooold 2018 Autocad software

**Comment by LAAP** [comment]
@agrignard ,

Done. I have save the furniture in the building.dxf file, in an old dxf version (R12) with furniture, chairs, and entrance

Please, notice that entrance = elevators and main stairs (as rectangles):

**Comment by agrignard** [comment]
Interesting... this is what I have no 
<img width="1181" alt="Screenshot 2020-06-25 at 16 08 53" src="https://user-images.githubusercontent.com/3928502/85735764-3d066880-b6fe-11ea-83b4-c1ec9dfdcac7.png">

It would be great if you can validate your fle by running DXF_Validator.gaml to be sure that it is still compatible

**Comment by agrignard** [comment]
<img width="459" alt="Screenshot 2020-06-25 at 16 10 39" src="https://user-images.githubusercontent.com/3928502/85736046-70e18e00-b6fe-11ea-97d9-0530c38b8582.png">

**Comment by agrignard** [comment]
Ah ok ... You put all the layer using Capital Case... I'll change that

**Comment by agrignard** [comment]
No more elevator? something is different from the other 
<img width="1256" alt="Screenshot 2020-06-25 at 16 14 15" src="https://user-images.githubusercontent.com/3928502/85736653-f5341100-b6fe-11ea-9d53-44880b530892.png">

**Comment by agrignard** [comment]
Can you just keep the original one (s it is the one working) and **JUST** put the chair and desk layer?

**Comment by agrignard** [comment]
Also the file is flipped compare to the other one

<img width="941" alt="Screenshot 2020-06-25 at 16 16 51" src="https://user-images.githubusercontent.com/3928502/85737072-578d1180-b6ff-11ea-8645-f88fd0e40ed1.png">

**Comment by LAAP** [comment]
@agrignard 
I have done as you wished

**Comment by agrignard** [comment]
Seems to work except for the elevators. I have only one close to opera

**Comment by LAAP** [comment]
@agrignard ,

OK. Let me fix it

**Comment by LAAP** [comment]
@agrignard 

Done, let me know if it is working now

**Comment by agrignard** [comment]
I don't know what is wrong with this fie but I cannot run the DailyRoutine model with it.

And the entrance became and elevator
<img width="1255" alt="Screenshot 2020-06-26 at 00 06 31" src="https://user-images.githubusercontent.com/3928502/85800256-eb330200-b740-11ea-840e-c613c0337160.png">

**Comment by LAAP** [comment]
@agrignard ,

Where is the furniture and chairs? 

I have not touched the layers from the previous model, I only have copy paste furniture, chairs and the drawing of stairs (it is confusing the drawing without stairs). I have no touche entrances. 

But yes. If I look to the Lawyer, "entrances", I see that only the four "Elevators_primary" are the entrance to the floor, which it makes sense to me.

I am saving the dxf now in R12, let's see

**Comment by agrignard** [comment]
@ptaillandier If you want ot have a look at building_LUIS_NEW.dxf i cannot instanciated DailyRoutine, maybe because there are two many elements like chair and furniture?

It's in the last commit

**Comment by agrignard** [comment]
We can at least load them in the DXFValidator 
<img width="1481" alt="Screenshot 2020-06-26 at 08 54 53" src="https://user-images.githubusercontent.com/3928502/85829391-cc595d80-b78a-11ea-91ea-6288cc5da9c7.png">

**Comment by LAAP** [comment]
@agrignard ,

It is looking good. Let me know if you need help with the dxf

**Comment by agrignard** [comment]
Ok great thanks @LAAP and @ptaillandier people are now going to the real desk 

<img width="1186" alt="Screenshot 2020-06-26 at 16 30 49" src="https://user-images.githubusercontent.com/3928502/85868364-73a9b500-b7ca-11ea-9d9c-26a1798cbe42.png">

**Comment by LAAP** [comment]
Awesome @agrignard and @ptaillandier!!!  Good job!!!! It is looking cool!!  ;)
