### ISSUE TITLE
CUCS building dxf production

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#77]
We will need to make the CUCS Office O compatible with proxymix. To do so we need to produce the right layer.

Here is the current dxf file
<img width="1177" alt="Screenshot 2020-06-29 at 17 36 23" src="https://user-images.githubusercontent.com/3928502/86026352-94267900-ba2f-11ea-8b94-df313ac23b73.png">

Here is the medialab case study
<img width="1652" alt="Screenshot 2020-06-29 at 17 39 45" src="https://user-images.githubusercontent.com/3928502/86026363-97ba0000-ba2f-11ea-8927-d549af2c0ecb.png">

**Comment by MarkusElKatsha** [comment]
Yes, can you point me to a layer structure/naming you would like to use?

**Comment by agrignard** [comment]
There is already a placeholder to host the building.dxf 

https://github.com/CityScope/CS_Proxymix/tree/master/ProxymixABM/includes/CUCS

Markus here is the file
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/MediaLab/building.dxf

**Comment by agrignard** [comment]
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/CUCS/new%20block2_R12_.dxf

**Comment by MarkusElKatsha** [comment]
These are the CAD standards we should always use: https://openlab.citytech.cuny.edu/arch-1230/files/2014/08/AIA-Layer-Standards.pdf

**Comment by LAAP** [comment]
Hi @agrignard and @MarkusElKatsha ,

I have done the ML one, so maybe it makes sense me doing also this other one. I can try to have it ready for tomorrow morning. 

Please, let me know your thoughts

**Comment by agrignard** [comment]
@nayoub is also working on it. But yes if you can have a look that would be great. The idea is to have a first iteration with the same spirit as the Medialab one

**Comment by LAAP** [comment]
Hi, id @nayoub or @MarkusElKatsha are already doing it, that is great! I step back then

**Comment by agrignard** [comment]
Well let's see i think there is lot of work here. and different level also. For now we decied to do the first level but there is also the groudn and the second level.

So it might take a lot of iteration in case, so the important thing is not to duplicate work and to coordinate on github with the right commit. @nayoub, let us know when you have a first version. 

I don't how long it can take for you guys to change the layer name, in any case ones it's done then we can feed the Gama model and see how it looks.

**Comment by LAAP** [comment]
@agrignard , you are right. I do not want to re do the work twice, so @nayoub please, let me know if you have time to do this today. if not, I will do it tonught

**Comment by agrignard** [comment]
And we now have to do the same for the entire Campus...
Here is the starting point
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/CUCS_Campus/PLANO%20DE%20CONJUNTO%20CUCS_LT2.dxf

<img width="1700" alt="Screenshot 2020-06-29 at 21 35 56" src="https://user-images.githubusercontent.com/3928502/86048318-9e0ca400-ba50-11ea-82c6-3d29a8656930.png">

**Comment by agrignard** [comment]
Thanks @nayoub the office O version beta is working (we still need to agree where to put offices, classrom etc) bu tthe structure is ok and running with the model (not yet for the real chair bu I will create a dedicated issue fr @ptaillandier )
<img width="1148" alt="Screenshot 2020-06-29 at 22 50 46" src="https://user-images.githubusercontent.com/3928502/86054820-1d06da00-ba5b-11ea-8c25-5839d44f5b2c.png">

next step that might be done today is the hole campus

**Comment by agrignard** [comment]
@nayoub 
Here is what I have for the hole campus it seems that something is wrong with the enveloppe (the enveloppe is too big). Also right now I cannot compute the pedestrian path on it. So something is wrong, let's find out what. Also it looks like all the oterh layer are here. I think it would be better to start form Scratch and copy paste the right layer instead of starting from the original file.

<img width="1119" alt="Screenshot 2020-06-30 at 09 17 41" src="https://user-images.githubusercontent.com/3928502/86095764-b1505b80-bab2-11ea-82c0-983e0122a03e.png">

**Comment by agrignard** [comment]
The enveloppe is now ok. Still some problem for the pedestrain Iam working on it.

Things that still need to be done related to this issue is to produce the ground floor and the second level for the Office O

**Comment by agrignard** [comment]
@LAAP and @nayoub do you think you will have time to produce the ground level and the second floor before friday?

**Comment by LAAP** [comment]
@agrignard , 
I can try, but not sure exactly what is the task. Also, At the end I think Carlos Ivan will have his meeting on Monday, so I can try tomorrow too

**Comment by agrignard** [comment]
The task is pretty clea:  Repeat what have been done by @nayoub that produces the first level from the original spanish version of the edificio O and to do it for the ground level and the 2nd level (mainly with entrance, offices/meeting romms and wall)

Do you see ?

**Comment by agrignard** [comment]
Level 2 seems ok (validated + pedestrain apth + Dailyroutine)
<img width="1210" alt="Screenshot 2020-07-02 at 21 51 16" src="https://user-images.githubusercontent.com/3928502/86403547-36539480-bcae-11ea-8056-6219a9a0f125.png">


Still an issue with Ground

**Comment by agrignard** [comment]
I close this issue as there is only #88 remaining
