### ISSUE TITLE
CAD Standards - Architectural Elements - Unifying Layer Names

### ISSUE THREAD

**Issue by MarkusElKatsha** [CityScope/CS_Proxymix#78]
AIA CAD Standards
https://openlab.citytech.cuny.edu/arch-1230/files/2014/08/AIA-Layer-Standards.pdf

**Comment by MarkusElKatsha** [comment]
ISO CAD standards for review: https://www.itcon.org/papers/itcon.paper.1997-2.pdf

**Comment by agrignard** [comment]
Thanks god @MarkusElKatsha is here!

So let's start the convertion so here is the current naming convetion (no standard) 
`````
	string walls <- "Walls";	
	string entrance <-"Entrance";
	string offices <- "Offices";
	string supermarket <-"Supermarket";
	string meeting_rooms <- "Meeting rooms";
	string coffee <- "Coffee";
	string storage <- "Storage";	
	string furnitures <- "Furniture";
	string toilets <- "Toilets";
	string elevators <- "Elevators";
	string stairs <- "Stairs";
	string doors <- "Doors";
	string chairs <- "Chair";
`````

**Comment by LAAP** [comment]
@agrignard and @MarkusElKatsha ,

Are we sure that we want to deal with ACAD-Architectural standards? 

¿?

**Comment by agrignard** [comment]
See #43 it's the same discussion at the end

**Comment by agrignard** [comment]
Food for thought 
https://register.apple.com/resources/imdf/

**Comment by agrignard** [comment]
Sure ;-) give me just a sec to refind Tim Cook phone number

**Comment by agrignard** [comment]
I archive the issue for now as I didn't find the time to talk to Tim Cook yet
