### ISSUE TITLE
Switching to 3D

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#79]
<img width="1605" alt="Screenshot 2020-06-30 at 00 19 12" src="https://user-images.githubusercontent.com/3928502/86061775-a9b79500-ba67-11ea-8ab1-55748360b907.png">
<img width="938" alt="Screenshot 2020-06-30 at 00 20 19" src="https://user-images.githubusercontent.com/3928502/86061781-aae8c200-ba67-11ea-981e-cc960b3f7b43.png">

https://github.com/CityScope/CS_Proxymix/tree/master/ProxymixABM/includes/Obj

**Comment by LAAP** [comment]
Why not? However, let's stick with the "basics" in this first phase, please, hahahah! After, we can go to the moon if you wish!

**Comment by agrignard** [comment]
@nayoub can you try to find a more iconized .obj?
