### ISSUE TITLE
1st Iteration deliverable

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#83]
Given a distance to respect between people what is the maximum number of people that can fit in a room?

Here are 4 screenshots with the number of maximum desk for each room given the distance.

This is for the 1st level we will need to make it for the ground floor and for the 2nd level. For this see issue #77  

<img width="1920" alt="Screenshot 2020-06-30 at 17 52 44" src="https://user-images.githubusercontent.com/3928502/86148265-b5a06700-bafa-11ea-8373-8f32b0f7a2c5.png">
<img width="1920" alt="Screenshot 2020-06-30 at 17 52 50" src="https://user-images.githubusercontent.com/3928502/86148277-b89b5780-bafa-11ea-82e9-668721d38b83.png">
<img width="1920" alt="Screenshot 2020-06-30 at 17 52 56" src="https://user-images.githubusercontent.com/3928502/86148280-b933ee00-bafa-11ea-83d0-0a4b30f18202.png">
<img width="1920" alt="Screenshot 2020-06-30 at 17 53 02" src="https://user-images.githubusercontent.com/3928502/86148286-b9cc8480-bafa-11ea-85d3-53aa8e24c314.png">

**Comment by LAAP** [comment]
Hi @agrignard 

I am working on this

**Comment by agrignard** [comment]
You mean to produce the ground floor and the second level dxf?

**Comment by LAAP** [comment]
Hi @agrignard ,

You are missing 2 Labs here:


<img width="243" alt="Captura de pantalla 2020-06-30 a las 17 37 31" src="https://user-images.githubusercontent.com/19315213/86179527-7113cc00-baf8-11ea-8abf-c29b827bdf2d.png">


And the 2 WC:

<img width="116" alt="Captura de pantalla 2020-06-30 a las 17 38 46" src="https://user-images.githubusercontent.com/19315213/86179639-a28c9780-baf8-11ea-841b-8b552bfc4d3e.png">

I will make a "strapolation"

**Comment by agrignard** [comment]
You can put it as labs (actually Offices or Meeting rooms) @nayoub did it like that because we just don't have the information right now so it's an "educated guess"

If you modifiy it please be sure that the file is still compatible (save to AutoCad 2013) and then all the procedure to be sure everything work is now written here https://github.com/CityScope/CS_Proxymix/wiki so more excuse to have non working dxf ;-)

**Comment by LAAP** [comment]
Hi @agrignard 

Base in IDSS this are times and People. Tomorrow I will study the "% of use" (density) and the shifts need to cover as much as possible of the time in the building:


Room | Pre-COVID-19 | Ramp-up 1.5m | Max Time min | Ramp-up 2m | Max Time min | Ramp-up 2.5m | Max Time min | Ramp-up 3m | Max Time min
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
WC Men | 5 | 3 |   | 2 |   | 2 |   | 1 |  
WC Women | 5 | 3 |   | 2 |   | 2 |   | 1 |  
LAB 201 | 10 | 10 | 84 | 10 | 84 | 10 | 84 | 10 | 84
LAB 202 | 10 | 10 | 84 | 10 | 84 | 10 | 84 | 10 | 84
Office (LAB) | 5 | 14 | 95 | 9 | 110 | 4 | 145 | 3 | 150
Educational Center | 30 | 55 | 45 | 32 | 57 | 21 | 72 | 15 | 92
Comité | 5 | 10 | 84 | 8 | 100 | 3 | 150 | 3 | 150
Clasroom 101 | 30 | 20 | 75 | 12 | 98 | 9 | 110 | 6 | 116
Clasroom 102 | 30 | 20 | 75 | 12 | 98 | 9 | 110 | 6 | 116
Clasroom 103 | 30 | 20 | 75 | 12 | 98 | 9 | 110 | 6 | 116
Clasroom 104 | 30 | 20 | 75 | 12 | 98 | 9 | 110 | 6 | 116
Clasroom 105 | 30 | 20 | 75 | 12 | 98 | 9 | 110 | 6 | 116
Clasroom 106 | 30 | 20 | 75 | 12 | 98 | 9 | 110 | 6 | 116
Clasroom 107 | 30 | 20 | 75 | 12 | 98 | 9 | 110 | 6 | 116
  |   |   |   |   |   |   |   |   |  
TOTAL per shift | 270 | 239 |   | 153 |   | 111 |   | 83 |  
TOTAL TIME |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |  
Students | 245 | 205 |   | 124 |   | 87 |   | 60 |  
Researchers | 20 | 20 |   | 20 |   | 20 |   | 20 |  
Staff | 5 | 14 |   | 9 |   | 4 |   | 3 |  



Note: Max time is calculated using MIT IDSS doc

**Comment by agrignard** [comment]
Whow that looks cool. I cannot imagine the time it took to make this in github ;-) maybe just a csv can be easier for you and also for them, and can be use to plot stuff. If we go in the csv mood we can also imagine to have Gama producing it. We just need to agree on what to put in it. I will make a first trial to export a csv output from the simulation

**Comment by agrignard** [comment]
OK I just did a first version here that will save a csv file with the following information

@LAAP You can try it if you want (run DailyRoutine and play with ````distance_people````

Name ````output2020-07-01 10:22:06distance_1.5.csv````

``````
type,length(entrances),length(available_places)
Meeting rooms,2,20
Meeting rooms,6,20
Meeting rooms,2,20
Meeting rooms,6,20
Meeting rooms,2,20
Meeting rooms,2,20
Meeting rooms,4,20
Offices,6,55
Offices,1,14
Offices,1,10
``````

**Comment by LAAP** [comment]
@agrignard ,

It takes 1 sec to copy paste from the csv.

I have pushed the csv file into the Github:

results < Handmade
csv file -  200630_Rooms and time

**Comment by LAAP** [comment]
@agrignard ,

I am running the tool, and it is looking very cool:

<img width="1431" alt="Captura de pantalla 2020-07-01 a las 11 00 21" src="https://user-images.githubusercontent.com/19315213/86259757-6a359980-bb8a-11ea-8c78-fc4c196101f3.png">

Also, I have the output of the 1st csv:


type | length(entrances) | length(available_places)
-- | -- | --
Offices | 2 | 133
Offices | 6 | 130
Offices | 2 | 128
Offices | 6 | 133
Offices | 2 | 133
Offices | 2 | 135
Offices | 4 | 136
Offices | 6 | 0
Offices | 1 | 0
Offices | 1 | 0


In next iterations, I think that it could be cool to know time that people can spend in the rooms in COVID era vs Pre-COVID era.

Some of the hours are in the csv file that I have incorporated in the folder "Handmade"

Also, what extra current-info could we "publish" in the current csv file coming from the current simulation? % of risky areas in m2 (from heatmaps)? Risk level in the building (Save areas - risky areas) in m2? etc?

**Comment by agrignard** [comment]
Nice!! it starts too look like something!

**Comment by LAAP** [comment]
Awesome @agrignard , 

So, if you can pic 3 or 4 "stuff" related to the heatmapsetc to show in the cvs it could be cool

**Comment by LAAP** [comment]
New table with time spended in the building, pre-COVID and ramps up:


Room | Pre-COVID-19 | TIME min | Time per person | Same density   COVID time | Max Time min | Time per person | Ramp-up 1.5m | Max Time min | Time per person | Ramp-up 2m | Max Time min | Time per person | Ramp-up 2.5m | Max Time min | Time per person | Ramp-up 3m | Max Time min | Time per person
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
WC Men | 5,00 |   |   | 5,00 |   |   | 3,00 |   |   | 2,00 |   |   | 2,00 |   |   | 1,00 |   |  
WC Women | 5,00 |   |   | 5,00 |   |   | 3,00 |   |   | 2,00 |   |   | 2,00 |   |   | 1,00 |   |  
LAB 201 | 10,00 | 480,00 | 4800,00 | 10,00 | 84,00 | 840,00 | 10,00 | 84,00 | 840,00 | 10,00 | 84,00 | 840,00 | 10,00 | 84,00 | 840,00 | 10,00 | 84,00 | 840,00
LAB 202 | 10,00 | 480,00 | 4800,00 | 10,00 | 84,00 | 840,00 | 10,00 | 84,00 | 840,00 | 10,00 | 84,00 | 840,00 | 10,00 | 84,00 | 840,00 | 10,00 | 84,00 | 840,00
Office   (LAB) | 5,00 | 480,00 | 2400,00 | 5,00 | 130,00 | 650,00 | 14,00 | 95,00 | 1330,00 | 9,00 | 110,00 | 990,00 | 4,00 | 145,00 | 580,00 | 3,00 | 150,00 | 450,00
Educational   Center | 30,00 | 480,00 | 14400,00 | 30,00 | 55,00 | 1650,00 | 55,00 | 45,00 | 2475,00 | 32,00 | 57,00 | 1824,00 | 21,00 | 72,00 | 1512,00 | 15,00 | 92,00 | 1380,00
Comité | 5,00 | 480,00 | 2400,00 | 5,00 | 84,00 | 420,00 | 10,00 | 84,00 | 840,00 | 8,00 | 100,00 | 800,00 | 3,00 | 150,00 | 450,00 | 3,00 | 150,00 | 450,00
Clasroom   101 | 30,00 | 180,00 | 5400,00 | 30,00 | 55,00 | 1650,00 | 20,00 | 75,00 | 1500,00 | 12,00 | 98,00 | 1176,00 | 9,00 | 110,00 | 990,00 | 6,00 | 116,00 | 696,00
Clasroom   102 | 30,00 | 180,00 | 5400,00 | 30,00 | 55,00 | 1650,00 | 20,00 | 75,00 | 1500,00 | 12,00 | 98,00 | 1176,00 | 9,00 | 110,00 | 990,00 | 6,00 | 116,00 | 696,00
Clasroom   103 | 30,00 | 180,00 | 5400,00 | 30,00 | 55,00 | 1650,00 | 20,00 | 75,00 | 1500,00 | 12,00 | 98,00 | 1176,00 | 9,00 | 110,00 | 990,00 | 6,00 | 116,00 | 696,00
Clasroom   104 | 30,00 | 180,00 | 5400,00 | 30,00 | 55,00 | 1650,00 | 20,00 | 75,00 | 1500,00 | 12,00 | 98,00 | 1176,00 | 9,00 | 110,00 | 990,00 | 6,00 | 116,00 | 696,00
Clasroom   105 | 30,00 | 180,00 | 5400,00 | 30,00 | 55,00 | 1650,00 | 20,00 | 75,00 | 1500,00 | 12,00 | 98,00 | 1176,00 | 9,00 | 110,00 | 990,00 | 6,00 | 116,00 | 696,00
Clasroom   106 | 30,00 | 180,00 | 5400,00 | 30,00 | 55,00 | 1650,00 | 20,00 | 75,00 | 1500,00 | 12,00 | 98,00 | 1176,00 | 9,00 | 110,00 | 990,00 | 6,00 | 116,00 | 696,00
Clasroom   107 | 30,00 | 180,00 | 5400,00 | 30,00 | 55,00 | 1650,00 | 20,00 | 75,00 | 1500,00 | 12,00 | 98,00 | 1176,00 | 9,00 | 110,00 | 990,00 | 6,00 | 116,00 | 696,00
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
TOTAL per   shift | 270,00 |   |   | 270,00 |   |   | 239,00 |   |   | 153,00 |   |   | 111,00 |   |   | 83,00 |   |  
TOTAL TIME   in min |   |   | 66600,00 |   |   | 15950,00 |   |   | 16825,00 |   |   | 13526,00 |   |   | 11152,00 |   |   | 8832,00
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Total   shifts |   |   |   |   |   | 4,18 |   |   | 3,96 |   |   | 4,92 |   |   | 5,97 |   |   | 7,54
% of time |   |   |   |   |   | 23,95 |   |   | 25,26 |   |   | 20,31 |   |   | 16,74 |   |   | 13,26
% of   people |   |   |   | 100,00 |   |   | 88,52 |   |   | 56,67 |   |   | 41,11 |   |   | 30,74 |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Students | 245,00 |   |   | 245,00 |   |   | 205,00 |   |   | 124,00 |   |   | 87,00 |   |   | 60,00 |   |  
Researchers | 20,00 |   |   | 20,00 |   |   | 20,00 |   |   | 20,00 |   |   | 20,00 |   |   | 20,00 |   |  
Staff | 5,00 |   |   | 5,00 |   |   | 14,00 |   |   | 9,00 |   |   | 4,00 |   |   | 3,00 |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
% time   Students |   |   |   |   |   | 30,56 |   |   | 27,78 |   |   | 21,78 |   |   | 18,33 |   |   | 12,89
Shift of   students |   |   |   | 1,00 |   |   | 1,20 |   |   | 1,98 |   |   | 2,82 |   |   | 4,08 |   |  
Shift of   Researchers |   |   |   | 1,00 |   |   | 1,00 |   |   | 1,00 |   |   | 1,00 |   |   | 1,00 |   |  
Shift of   staff |   |   |   | 1,00 |   |   | 0,36 |   |   | 0,56 |   |   | 1,25 |   |   | 1,67 |   |
