### ISSUE TITLE
Too many chair in CUCS

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#86]
@nayoub do you think we can simplify the chair layer?

<img width="1098" alt="Screenshot 2020-07-01 at 19 40 57" src="https://user-images.githubusercontent.com/3928502/86275108-0aafac00-bbd3-11ea-909b-95db9d6b1a8e.png">

**Comment by nayoub** [comment]
Sure no problem. I can do it today

________________________________

**Comment by agrignard** [comment]
OK it s now working
<img width="1377" alt="Screenshot 2020-07-02 at 10 19 41" src="https://user-images.githubusercontent.com/3928502/86334510-9534f180-bc4d-11ea-85ae-d1269c208f32.png">
