### ISSUE TITLE
Level 1 dxf confusion

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#89]
In the current dxf there are 3 offices and 7 class rooms.

@LAAP in one of your slide i saw you put it to 10 class rooms. Why not but please be careful to always update or the corresponding building.dxf so that we all run the same simulation or maybe @nayoub you did a change

<img width="924" alt="Screenshot 2020-07-03 at 10 05 45" src="https://user-images.githubusercontent.com/3928502/86446845-c9bfb080-bd14-11ea-9878-7e64ae12edc3.png">

Any way the  the current Level 1/building.dxf is currently  3 offices and 7 class rooms. Please feel free to update it (but be sure that it doesn't break anything) 
<img width="1194" alt="Screenshot 2020-07-03 at 10 06 54" src="https://user-images.githubusercontent.com/3928502/86446962-f247aa80-bd14-11ea-9753-0ac65cd41e73.png">

**Comment by LAAP** [comment]
@agrignard , I will close this issue. It was a "placeholder image" of one of my cool tests

**Comment by agrignard** [comment]
I think you confuse with another issue, no? This is an issue has the dxf in the github has 3 offices and 7 meetings and you ahd a version with only Offices. So I depends on what we want to keep. But I think you have the dxf in local no?

**Comment by LAAP** [comment]
@agrignard .... Mmmmm. I didn't add any version as far as I know...

**Comment by nayoub** [comment]
I didn’t make any changes, it was 3 offices and the rest meeting rooms but we can change it if you prefer wi try only offices?

________________________________

**Comment by agrignard** [comment]
What I don't get is that @LAAP you show in an issue a screenshot with 10 offices instead of 3 and 7 Meetings rooms. If it's ok as it is now in the Github we can close this issue (just people don't go in the meeting rooms)

**Comment by LAAP** [comment]
@agrignard , Yes, the number "10" Emerges when you have a physical distance smaller than 2m

**Comment by agrignard** [comment]
No as you can see on the 2 screenshot I put in the first comment of this issue I was speaking about 10 offices as spaces ( not 10 desk in an office). So it meansat some point you have created this modified dxf but nevrmind let's not create issue if there is no issue there is enough other stiff to do.
