### ISSUE TITLE
Research Question for a ready to use tool for reopening space 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#90]
Hi everyone, Would be great to have your input to all of you (@ptaillandier , @tnguyenh , @LAAP and @Markus (I don't why I cannot tag you maybe you should contribute at least ones in this repo ;-) )

So we have been doing a great push this last weeks (big thanks to @ptaillandier for the GAMA part and @nayoub for the dxf part). So we now have an ABM model pretty robust but that doesn't really answer to any question yet. From the beginning, we are kidn of exploring with the ABM approach on the building scale and it was hard to find a real question?

There is now a clear request from different actor, (academic but also private) to have a ready to use tool to help the reoping of the space. I start to believe that this proxymix tool could be a good one.

To do so I propose here a kind of framework that could be accomplished by GAMA. For me there are 2 main task here:

1. Being able to evaluate the riskness of a specific layout

For this I think we need to explore a new way to evaluate the riskness of the space by using a kind of pollution-like model. Assuming that people emits a certains number of particules depending on their profile activity (for this the idea would be to base our knowledge on this study https://idss.mit.edu/research/idss-covid-19-collaboration-isolat/)

What I'd like to see is put all the people at there desk let them live, and see how the air of the room slowly becomes polluted using a grid and maybe a diffusion process). Then this heatmap would be the metrics for the quality of the room. For a first step I don't thin people need to move (or just like going to the toilets and maybe checking a colleagues some time). 

2. Being able to propose programmatically a "better" layout (this might induce an optimisation problem which is maybe not that straightforward, however I have the feeling that with little constraint we can propose a "better layout" than the existing one. The idea is thus  to generate a better layout that will end up is a cleaner room and also on top of the layout why not also proposing a temporal readjustement (time shifting) of the schedule of the people.

I don't know if this is clear enough, I think we should definitely schedule a meeting with @ptaillandier and @tnguyenh to see how it can be effectively conceptualise in an Agent World and implemented in GAMA.

**Comment by LAAP** [comment]
@agrignard ,

I agree, 1 and 2 are the main goals for the simulation

**Comment by agrignard** [comment]
See #92 for one way to evaluate the riskness of a specific layout

**Comment by agrignard** [comment]
Outdated
