### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Proxymix#91]
Hi @agrignard ,

I have found this error:

1 occurence in people13 at cycle 1194: Cannot evaluate entrances as the target agent is nil
in target <- closest_to(target_room.entrances,self);
in target <- closest_to(target_room.entrances,self);
in agent people13

<img width="1433" alt="Captura de pantalla 2020-07-03 a las 18 21 44" src="https://user-images.githubusercontent.com/19315213/86499622-3f9a3b00-bd5a-11ea-98a9-952cd10cb2af.png">

**Comment by agrignard** [comment]
Hi @LAAP with which file is this happening? Which level? Is it always happening?

**Comment by LAAP** [comment]
mmmmmmm.... No idea.... @agrignard ... I am just running the simulation normally

**Comment by agrignard** [comment]
Ok I can have it to but not always right?
````
1 occurence in people13 at cycle 334: Cannot evaluate entrances as the target agent is nil
in target <- closest_to(target_room.entrances,self);
in target <- closest_to(target_room.entrances,self);
in agent people13
````

However this is just a warning not an error. but we will check what happens here
