### ISSUE TITLE
Windows layer integration

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#93]
Following the differnet discussion we have had the last few days, we'd like to see the effect of ventilation and so the effect on windows on the spreading of the droplet for this we need to have a new layer window for the dxfs 

@milkmonica , @nayoub , @LAAP and Markus how do we proceed? The idea would be to add to the existing dxfs file a window layer and then we will see with @ptaillandier how to integrate it in the model.

**Comment by LAAP** [comment]
Hi @agrignard ,

I think that we should simulate windows as well as "conventional" air conditioning. 

It will depend a bit on how the model will work. As far as I can imagine, there are 2 options:

1) The complex one: If we have a good fluiddynamik model, combined with the Gama diffusion model, etc. we can give you the inputs of air (windows, fans, air nozzles, etc.) and the outputs (doors, or other windows, air return grid, etc), as well as number of air renovations per minute, and then we can try to simulate the "turbulences" in the room.

2) Simpler: To find a diagram like the one from the IDSS where time and number of people in a room are determined already for each different ventilation type:

<img width="311" alt="Captura de pantalla 2020-07-20 a las 19 53 12" src="https://user-images.githubusercontent.com/19315213/88062149-6caa6400-cb36-11ea-9803-1e3101e08fb1.png">

And build a model that just measures time in the room and distance between people depending on the air conditioning system of the room

**Comment by milkmonica** [comment]
For this simulation, in the .dxf I put a separate layer called "Windows" (although for now is not declared in gama)

I draw these objects as an individuals rectangles (window by window) I also separate the glass from the aluminum profiles (this profiles are in "Wall" layer) ![IMG-20200806-WA0012](https://user-images.githubusercontent.com/7746716/90153155-3b484100-dd4e-11ea-91f0-515886d53000.jpeg)

**Comment by agrignard** [comment]
Not specific enough . I close this isse
