### ISSUE TITLE
CUT Integration 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#95]
Well done @gamalielpalomo and @milkmonica , we have the first dxf. 

<img width="1128" alt="Screenshot 2020-08-12 at 23 28 14" src="https://user-images.githubusercontent.com/3928502/90070106-9dc02380-dcf3-11ea-825f-cac8afa7f13d.png">

We need now to make it compatible with the simulation here are the layer missing  (I had to change the capital case to small case (something related to autocad (save in autocad 2013)

<img width="519" alt="Screenshot 2020-08-12 at 23 28 04" src="https://user-images.githubusercontent.com/3928502/90070131-a9134f00-dcf3-11ea-94ca-130fd68efd08.png">

**Comment by gamalielpalomo** [comment]
- Furniture layer is already in the dxf, the name has a typo
- I think we need to add the validation for windows as this building has a lot of them. This is why the result seems empty of walls
- Also, gama it appears in the wrong orientation, the following is a snapshot from autocad
![image](https://user-images.githubusercontent.com/19692636/90088098-d6580100-dce3-11ea-96dd-aff64fd66a87.png)

**Comment by gamalielpalomo** [comment]
![image](https://user-images.githubusercontent.com/19692636/90092992-1e7d2080-dcf0-11ea-9974-50ed4a372e19.png)
For now this is the pedestrian paths network and the walking area generated with the file in the current state. I dont know exactly how the generator algorithm works, is it a good idea to put windows (color:blue) as walls?

**Comment by agrignard** [comment]
Window are now taking in account (but not yet in the pedestrain network) but there are still mandatory layer that are missing especilly: Entrance (where peopel arrive in the building, and Offices
<img width="1030" alt="Screenshot 2020-08-13 at 12 14 55" src="https://user-images.githubusercontent.com/3928502/90123165-aa2d9600-dd5e-11ea-8239-cd5bb3be18b3.png">


<img width="520" alt="Screenshot 2020-08-13 at 12 14 49" src="https://user-images.githubusercontent.com/3928502/90123160-a8fc6900-dd5e-11ea-89d9-60773ee8c9ae.png">

**Comment by agrignard** [comment]
Awesome!!
