### ISSUE TITLE
CUT dxf 180 rotation

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#96]
Right now the dxf opened in Autocad and in Gama is flipped 180°

@gamalielpalomo and @milkmonica can you make the change?

**Comment by milkmonica** [comment]
Yes, although I would like to know why the .dfx export makes these changes, especially to prevent this from happening again... and in that case rotate all the centers before uploading them, or download the 2018 version of autocad. (I have 2021)

**Comment by agrignard** [comment]
I don't think it's the export of Autocad, it's the way GAMA handle dxf file (the Y is down) and in Autocad I guess the Y is up.

So for now, even though it's not very clean but at least we have something running, it shoudl be rotated in Autocad and then save like this.

**Comment by gamalielpalomo** [comment]
Issue solved with new PR.
