### ISSUE TITLE
CUT dxf formalization

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#98]
Right now in the CUT dxf it seems that we have only one classrooms and one Labs.

What about the other spaces? I would expect to have more Offices and Meetings Rooms. 

@milkmonica can you tell us a bit more about what you think on this one? 

<img width="1031" alt="Screenshot 2020-08-13 at 12 35 43" src="https://user-images.githubusercontent.com/3928502/90125016-959ecd00-dd61-11ea-9e38-8675aa76aa66.png">

**Comment by milkmonica** [comment]
Yes, the original idea (following Luis suggestions to make quick drawings) was making strategic decitions about simulate only one type of scenario for each campus (for example: ventilation, access points, etc). 

The original idea for C.U.T was to simulate only one classroom and only one lab, but now we think its a better idea to use the complete building to simulate the students  flows.

 Gama and I are preparing a quick presentation fo these choices, this is the link:
https://docs.google.com/presentation/d/1FB-eWkUBE34tVvbnjmbQWSHPb83gRDwl4pF9zTi9flY/edit#slide=id.g9080ba01df_0_41

**Comment by agrignard** [comment]
There is still no Offices in this dxf... so the model cannot run as it is implemented.

**Comment by gamalielpalomo** [comment]
We really needed to do a little trick with the problem with offices. We have put classrooms as offices (though really they are not offices) for the model to run with the dxf.

**Comment by agrignard** [comment]
Now that the dxf works well we can  think about adding the classrooms with the same behavior as the office. I have created a dedicated issue #103
